//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/extensions/filters/udp/dynamic_modules/v3/dynamic_modules.proto

package dynamic_modulesv3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DynamicModuleUdpListenerFilter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DynamicModuleUdpListenerFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DynamicModuleUdpListenerFilter with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DynamicModuleUdpListenerFilterMultiError, or nil if none found.
func (m *DynamicModuleUdpListenerFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *DynamicModuleUdpListenerFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDynamicModuleConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DynamicModuleUdpListenerFilterValidationError{
					field:  "DynamicModuleConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DynamicModuleUdpListenerFilterValidationError{
					field:  "DynamicModuleConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDynamicModuleConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DynamicModuleUdpListenerFilterValidationError{
				field:  "DynamicModuleConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for FilterName

	if all {
		switch v := interface{}(m.GetFilterConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DynamicModuleUdpListenerFilterValidationError{
					field:  "FilterConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DynamicModuleUdpListenerFilterValidationError{
					field:  "FilterConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilterConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DynamicModuleUdpListenerFilterValidationError{
				field:  "FilterConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DynamicModuleUdpListenerFilterMultiError(errors)
	}

	return nil
}

// DynamicModuleUdpListenerFilterMultiError is an error wrapping multiple
// validation errors returned by DynamicModuleUdpListenerFilter.ValidateAll()
// if the designated constraints aren't met.
type DynamicModuleUdpListenerFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DynamicModuleUdpListenerFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DynamicModuleUdpListenerFilterMultiError) AllErrors() []error { return m }

// DynamicModuleUdpListenerFilterValidationError is the validation error
// returned by DynamicModuleUdpListenerFilter.Validate if the designated
// constraints aren't met.
type DynamicModuleUdpListenerFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DynamicModuleUdpListenerFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DynamicModuleUdpListenerFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DynamicModuleUdpListenerFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DynamicModuleUdpListenerFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DynamicModuleUdpListenerFilterValidationError) ErrorName() string {
	return "DynamicModuleUdpListenerFilterValidationError"
}

// Error satisfies the builtin error interface
func (e DynamicModuleUdpListenerFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDynamicModuleUdpListenerFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DynamicModuleUdpListenerFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DynamicModuleUdpListenerFilterValidationError{}
