// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/listener/v3/listener_components.proto

package envoy_config_listener_v3

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	v31 "github.com/envoyproxy/go-control-plane/envoy/extensions/transport_sockets/tls/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterChainMatch_ConnectionSourceType int32

const (
	FilterChainMatch_ANY                 FilterChainMatch_ConnectionSourceType = 0
	FilterChainMatch_SAME_IP_OR_LOOPBACK FilterChainMatch_ConnectionSourceType = 1
	FilterChainMatch_EXTERNAL            FilterChainMatch_ConnectionSourceType = 2
)

var FilterChainMatch_ConnectionSourceType_name = map[int32]string{
	0: "ANY",
	1: "SAME_IP_OR_LOOPBACK",
	2: "EXTERNAL",
}

var FilterChainMatch_ConnectionSourceType_value = map[string]int32{
	"ANY":                 0,
	"SAME_IP_OR_LOOPBACK": 1,
	"EXTERNAL":            2,
}

func (x FilterChainMatch_ConnectionSourceType) String() string {
	return proto.EnumName(FilterChainMatch_ConnectionSourceType_name, int32(x))
}

func (FilterChainMatch_ConnectionSourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87f255d2eccc91b5, []int{1, 0}
}

type Filter struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//	*Filter_HiddenEnvoyDeprecatedConfig
	//	*Filter_TypedConfig
	ConfigType           isFilter_ConfigType `protobuf_oneof:"config_type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f255d2eccc91b5, []int{0}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isFilter_ConfigType interface {
	isFilter_ConfigType()
}

type Filter_HiddenEnvoyDeprecatedConfig struct {
	HiddenEnvoyDeprecatedConfig *_struct.Struct `protobuf:"bytes,2,opt,name=hidden_envoy_deprecated_config,json=hiddenEnvoyDeprecatedConfig,proto3,oneof"`
}

type Filter_TypedConfig struct {
	TypedConfig *any.Any `protobuf:"bytes,4,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*Filter_HiddenEnvoyDeprecatedConfig) isFilter_ConfigType() {}

func (*Filter_TypedConfig) isFilter_ConfigType() {}

func (m *Filter) GetConfigType() isFilter_ConfigType {
	if m != nil {
		return m.ConfigType
	}
	return nil
}

// Deprecated: Do not use.
func (m *Filter) GetHiddenEnvoyDeprecatedConfig() *_struct.Struct {
	if x, ok := m.GetConfigType().(*Filter_HiddenEnvoyDeprecatedConfig); ok {
		return x.HiddenEnvoyDeprecatedConfig
	}
	return nil
}

func (m *Filter) GetTypedConfig() *any.Any {
	if x, ok := m.GetConfigType().(*Filter_TypedConfig); ok {
		return x.TypedConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Filter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Filter_HiddenEnvoyDeprecatedConfig)(nil),
		(*Filter_TypedConfig)(nil),
	}
}

type FilterChainMatch struct {
	DestinationPort      *wrappers.UInt32Value                 `protobuf:"bytes,8,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	PrefixRanges         []*v3.CidrRange                       `protobuf:"bytes,3,rep,name=prefix_ranges,json=prefixRanges,proto3" json:"prefix_ranges,omitempty"`
	AddressSuffix        string                                `protobuf:"bytes,4,opt,name=address_suffix,json=addressSuffix,proto3" json:"address_suffix,omitempty"`
	SuffixLen            *wrappers.UInt32Value                 `protobuf:"bytes,5,opt,name=suffix_len,json=suffixLen,proto3" json:"suffix_len,omitempty"`
	SourceType           FilterChainMatch_ConnectionSourceType `protobuf:"varint,12,opt,name=source_type,json=sourceType,proto3,enum=envoy.config.listener.v3.FilterChainMatch_ConnectionSourceType" json:"source_type,omitempty"`
	SourcePrefixRanges   []*v3.CidrRange                       `protobuf:"bytes,6,rep,name=source_prefix_ranges,json=sourcePrefixRanges,proto3" json:"source_prefix_ranges,omitempty"`
	SourcePorts          []uint32                              `protobuf:"varint,7,rep,packed,name=source_ports,json=sourcePorts,proto3" json:"source_ports,omitempty"`
	ServerNames          []string                              `protobuf:"bytes,11,rep,name=server_names,json=serverNames,proto3" json:"server_names,omitempty"`
	TransportProtocol    string                                `protobuf:"bytes,9,opt,name=transport_protocol,json=transportProtocol,proto3" json:"transport_protocol,omitempty"`
	ApplicationProtocols []string                              `protobuf:"bytes,10,rep,name=application_protocols,json=applicationProtocols,proto3" json:"application_protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *FilterChainMatch) Reset()         { *m = FilterChainMatch{} }
func (m *FilterChainMatch) String() string { return proto.CompactTextString(m) }
func (*FilterChainMatch) ProtoMessage()    {}
func (*FilterChainMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f255d2eccc91b5, []int{1}
}

func (m *FilterChainMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterChainMatch.Unmarshal(m, b)
}
func (m *FilterChainMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterChainMatch.Marshal(b, m, deterministic)
}
func (m *FilterChainMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterChainMatch.Merge(m, src)
}
func (m *FilterChainMatch) XXX_Size() int {
	return xxx_messageInfo_FilterChainMatch.Size(m)
}
func (m *FilterChainMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterChainMatch.DiscardUnknown(m)
}

var xxx_messageInfo_FilterChainMatch proto.InternalMessageInfo

func (m *FilterChainMatch) GetDestinationPort() *wrappers.UInt32Value {
	if m != nil {
		return m.DestinationPort
	}
	return nil
}

func (m *FilterChainMatch) GetPrefixRanges() []*v3.CidrRange {
	if m != nil {
		return m.PrefixRanges
	}
	return nil
}

func (m *FilterChainMatch) GetAddressSuffix() string {
	if m != nil {
		return m.AddressSuffix
	}
	return ""
}

func (m *FilterChainMatch) GetSuffixLen() *wrappers.UInt32Value {
	if m != nil {
		return m.SuffixLen
	}
	return nil
}

func (m *FilterChainMatch) GetSourceType() FilterChainMatch_ConnectionSourceType {
	if m != nil {
		return m.SourceType
	}
	return FilterChainMatch_ANY
}

func (m *FilterChainMatch) GetSourcePrefixRanges() []*v3.CidrRange {
	if m != nil {
		return m.SourcePrefixRanges
	}
	return nil
}

func (m *FilterChainMatch) GetSourcePorts() []uint32 {
	if m != nil {
		return m.SourcePorts
	}
	return nil
}

func (m *FilterChainMatch) GetServerNames() []string {
	if m != nil {
		return m.ServerNames
	}
	return nil
}

func (m *FilterChainMatch) GetTransportProtocol() string {
	if m != nil {
		return m.TransportProtocol
	}
	return ""
}

func (m *FilterChainMatch) GetApplicationProtocols() []string {
	if m != nil {
		return m.ApplicationProtocols
	}
	return nil
}

type FilterChain struct {
	FilterChainMatch                *FilterChainMatch         `protobuf:"bytes,1,opt,name=filter_chain_match,json=filterChainMatch,proto3" json:"filter_chain_match,omitempty"`
	HiddenEnvoyDeprecatedTlsContext *v31.DownstreamTlsContext `protobuf:"bytes,2,opt,name=hidden_envoy_deprecated_tls_context,json=hiddenEnvoyDeprecatedTlsContext,proto3" json:"hidden_envoy_deprecated_tls_context,omitempty"` // Deprecated: Do not use.
	Filters                         []*Filter                 `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	UseProxyProto                   *wrappers.BoolValue       `protobuf:"bytes,4,opt,name=use_proxy_proto,json=useProxyProto,proto3" json:"use_proxy_proto,omitempty"`
	Metadata                        *v3.Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransportSocket                 *v3.TransportSocket       `protobuf:"bytes,6,opt,name=transport_socket,json=transportSocket,proto3" json:"transport_socket,omitempty"`
	Name                            string                    `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                  `json:"-"`
	XXX_unrecognized                []byte                    `json:"-"`
	XXX_sizecache                   int32                     `json:"-"`
}

func (m *FilterChain) Reset()         { *m = FilterChain{} }
func (m *FilterChain) String() string { return proto.CompactTextString(m) }
func (*FilterChain) ProtoMessage()    {}
func (*FilterChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f255d2eccc91b5, []int{2}
}

func (m *FilterChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterChain.Unmarshal(m, b)
}
func (m *FilterChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterChain.Marshal(b, m, deterministic)
}
func (m *FilterChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterChain.Merge(m, src)
}
func (m *FilterChain) XXX_Size() int {
	return xxx_messageInfo_FilterChain.Size(m)
}
func (m *FilterChain) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterChain.DiscardUnknown(m)
}

var xxx_messageInfo_FilterChain proto.InternalMessageInfo

func (m *FilterChain) GetFilterChainMatch() *FilterChainMatch {
	if m != nil {
		return m.FilterChainMatch
	}
	return nil
}

// Deprecated: Do not use.
func (m *FilterChain) GetHiddenEnvoyDeprecatedTlsContext() *v31.DownstreamTlsContext {
	if m != nil {
		return m.HiddenEnvoyDeprecatedTlsContext
	}
	return nil
}

func (m *FilterChain) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *FilterChain) GetUseProxyProto() *wrappers.BoolValue {
	if m != nil {
		return m.UseProxyProto
	}
	return nil
}

func (m *FilterChain) GetMetadata() *v3.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *FilterChain) GetTransportSocket() *v3.TransportSocket {
	if m != nil {
		return m.TransportSocket
	}
	return nil
}

func (m *FilterChain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListenerFilter struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//	*ListenerFilter_HiddenEnvoyDeprecatedConfig
	//	*ListenerFilter_TypedConfig
	ConfigType           isListenerFilter_ConfigType `protobuf_oneof:"config_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListenerFilter) Reset()         { *m = ListenerFilter{} }
func (m *ListenerFilter) String() string { return proto.CompactTextString(m) }
func (*ListenerFilter) ProtoMessage()    {}
func (*ListenerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f255d2eccc91b5, []int{3}
}

func (m *ListenerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerFilter.Unmarshal(m, b)
}
func (m *ListenerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerFilter.Marshal(b, m, deterministic)
}
func (m *ListenerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerFilter.Merge(m, src)
}
func (m *ListenerFilter) XXX_Size() int {
	return xxx_messageInfo_ListenerFilter.Size(m)
}
func (m *ListenerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerFilter proto.InternalMessageInfo

func (m *ListenerFilter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isListenerFilter_ConfigType interface {
	isListenerFilter_ConfigType()
}

type ListenerFilter_HiddenEnvoyDeprecatedConfig struct {
	HiddenEnvoyDeprecatedConfig *_struct.Struct `protobuf:"bytes,2,opt,name=hidden_envoy_deprecated_config,json=hiddenEnvoyDeprecatedConfig,proto3,oneof"`
}

type ListenerFilter_TypedConfig struct {
	TypedConfig *any.Any `protobuf:"bytes,3,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*ListenerFilter_HiddenEnvoyDeprecatedConfig) isListenerFilter_ConfigType() {}

func (*ListenerFilter_TypedConfig) isListenerFilter_ConfigType() {}

func (m *ListenerFilter) GetConfigType() isListenerFilter_ConfigType {
	if m != nil {
		return m.ConfigType
	}
	return nil
}

// Deprecated: Do not use.
func (m *ListenerFilter) GetHiddenEnvoyDeprecatedConfig() *_struct.Struct {
	if x, ok := m.GetConfigType().(*ListenerFilter_HiddenEnvoyDeprecatedConfig); ok {
		return x.HiddenEnvoyDeprecatedConfig
	}
	return nil
}

func (m *ListenerFilter) GetTypedConfig() *any.Any {
	if x, ok := m.GetConfigType().(*ListenerFilter_TypedConfig); ok {
		return x.TypedConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListenerFilter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListenerFilter_HiddenEnvoyDeprecatedConfig)(nil),
		(*ListenerFilter_TypedConfig)(nil),
	}
}

func init() {
	proto.RegisterEnum("envoy.config.listener.v3.FilterChainMatch_ConnectionSourceType", FilterChainMatch_ConnectionSourceType_name, FilterChainMatch_ConnectionSourceType_value)
	proto.RegisterType((*Filter)(nil), "envoy.config.listener.v3.Filter")
	proto.RegisterType((*FilterChainMatch)(nil), "envoy.config.listener.v3.FilterChainMatch")
	proto.RegisterType((*FilterChain)(nil), "envoy.config.listener.v3.FilterChain")
	proto.RegisterType((*ListenerFilter)(nil), "envoy.config.listener.v3.ListenerFilter")
}

func init() {
	proto.RegisterFile("envoy/config/listener/v3/listener_components.proto", fileDescriptor_87f255d2eccc91b5)
}

var fileDescriptor_87f255d2eccc91b5 = []byte{
	// 993 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6f, 0xe2, 0x46,
	0x14, 0x5e, 0x03, 0x4b, 0xc8, 0x18, 0x12, 0x77, 0x9a, 0x2a, 0x6e, 0x36, 0x4a, 0x08, 0xe9, 0x46,
	0x68, 0xab, 0x35, 0x12, 0xf4, 0xd2, 0xf4, 0x50, 0xc5, 0x24, 0xab, 0xdd, 0x6d, 0x7e, 0x50, 0x87,
	0x56, 0xdb, 0x93, 0x35, 0xb1, 0x07, 0xe2, 0xd6, 0xcc, 0x58, 0x33, 0x03, 0x0b, 0xd7, 0x9e, 0x56,
	0xbd, 0xb5, 0xc7, 0xfe, 0x3f, 0x55, 0xff, 0xa7, 0x1c, 0xba, 0xd5, 0xcc, 0xd8, 0x10, 0x08, 0x69,
	0x72, 0xec, 0xcd, 0x7e, 0xef, 0x7b, 0x1f, 0xef, 0xc7, 0xf7, 0x9e, 0x01, 0x4d, 0x4c, 0x46, 0x74,
	0xd2, 0x08, 0x28, 0xe9, 0x45, 0xfd, 0x46, 0x1c, 0x71, 0x81, 0x09, 0x66, 0x8d, 0x51, 0x6b, 0xfa,
	0xec, 0x07, 0x74, 0x90, 0x50, 0x82, 0x89, 0xe0, 0x4e, 0xc2, 0xa8, 0xa0, 0xd0, 0x56, 0x31, 0x8e,
	0x8e, 0x71, 0x32, 0x9c, 0x33, 0x6a, 0x6d, 0xd5, 0xe6, 0xd8, 0x02, 0xca, 0xb0, 0x64, 0x42, 0x61,
	0xc8, 0x30, 0x4f, 0xa3, 0xb7, 0x76, 0x97, 0x62, 0xae, 0x10, 0xc7, 0x29, 0xe0, 0x2b, 0x0d, 0xc0,
	0x63, 0x81, 0x09, 0x8f, 0x28, 0xe1, 0x0d, 0xc1, 0x10, 0xe1, 0x09, 0x65, 0xc2, 0xe7, 0x34, 0xf8,
	0x05, 0x0b, 0xde, 0x10, 0x31, 0x97, 0x51, 0x01, 0x66, 0x22, 0x8d, 0xfa, 0xbc, 0x4f, 0x69, 0x3f,
	0xc6, 0x0d, 0xf5, 0x76, 0x35, 0xec, 0x35, 0x10, 0x99, 0xa4, 0xae, 0xed, 0x45, 0x17, 0x17, 0x6c,
	0x18, 0x64, 0x81, 0x3b, 0x8b, 0xde, 0xf7, 0x0c, 0x25, 0x09, 0x66, 0x59, 0xbe, 0x7b, 0xc3, 0x30,
	0x41, 0x0d, 0x44, 0x08, 0x15, 0x48, 0xa8, 0x74, 0x46, 0x98, 0xc9, 0xbc, 0x22, 0xd2, 0x4f, 0x21,
	0x9b, 0x23, 0x14, 0x47, 0x21, 0x12, 0xb8, 0x91, 0x3d, 0x68, 0x47, 0xed, 0x1f, 0x03, 0x14, 0x5f,
	0x45, 0xb1, 0xc0, 0x0c, 0x3e, 0x03, 0x05, 0x82, 0x06, 0xd8, 0x36, 0xaa, 0x46, 0x7d, 0xd5, 0x5d,
	0xb9, 0x71, 0x0b, 0x2c, 0x57, 0x35, 0x3c, 0x65, 0x84, 0x57, 0x60, 0xe7, 0x3a, 0x0a, 0x43, 0x4c,
	0x7c, 0x55, 0xbb, 0x1f, 0xe2, 0x84, 0xe1, 0x00, 0x09, 0x1c, 0xfa, 0xba, 0x4f, 0x76, 0xae, 0x6a,
	0xd4, 0xcd, 0xe6, 0xa6, 0xa3, 0x93, 0x75, 0xb2, 0x64, 0x9d, 0x4b, 0x55, 0x8a, 0x9b, 0xb3, 0x8d,
	0xd7, 0x4f, 0xbc, 0x67, 0x9a, 0xe4, 0x44, 0x72, 0x1c, 0x4f, 0x29, 0xda, 0x8a, 0x01, 0x7e, 0x0d,
	0xca, 0x62, 0x92, 0xcc, 0x18, 0x0b, 0x8a, 0x71, 0xe3, 0x0e, 0xe3, 0x11, 0x99, 0xbc, 0x7e, 0xe2,
	0x99, 0x0a, 0xab, 0x43, 0x0f, 0xf7, 0xff, 0xfc, 0xeb, 0xc3, 0xce, 0x0e, 0xd8, 0xd6, 0x73, 0x47,
	0x49, 0xe4, 0x8c, 0x9a, 0xb3, 0xb9, 0xeb, 0x02, 0xdd, 0x0a, 0x30, 0x35, 0xb3, 0x2f, 0x43, 0xdf,
	0x16, 0x4a, 0x79, 0xab, 0x50, 0xfb, 0xad, 0x08, 0x2c, 0xed, 0x6f, 0x5f, 0xa3, 0x88, 0x9c, 0x21,
	0x11, 0x5c, 0xc3, 0x2e, 0xb0, 0x42, 0xcc, 0x45, 0x44, 0x54, 0x3f, 0x7d, 0x39, 0x58, 0xbb, 0xa4,
	0xb2, 0xd9, 0xbe, 0x93, 0xcd, 0x0f, 0x6f, 0x88, 0x68, 0x35, 0x7f, 0x44, 0xf1, 0x10, 0xbb, 0xe6,
	0x8d, 0x5b, 0x7a, 0x51, 0xb4, 0x3f, 0x7e, 0xcc, 0xd7, 0x0d, 0x6f, 0xfd, 0x16, 0x45, 0x87, 0x32,
	0x01, 0x8f, 0x41, 0x25, 0x61, 0xb8, 0x17, 0x8d, 0x7d, 0x86, 0x48, 0x1f, 0x73, 0x3b, 0x5f, 0xcd,
	0xd7, 0xcd, 0xe6, 0xae, 0x33, 0xa7, 0x56, 0xa9, 0x37, 0x67, 0xd4, 0x72, 0xda, 0x51, 0xc8, 0x3c,
	0x89, 0xf3, 0xca, 0x3a, 0x4a, 0xbd, 0x70, 0xf8, 0x1c, 0xac, 0xa5, 0x72, 0xf5, 0xf9, 0xb0, 0xd7,
	0x8b, 0xc6, 0xaa, 0x4f, 0xab, 0x5e, 0x25, 0xb5, 0x5e, 0x2a, 0x23, 0xfc, 0x06, 0x00, 0xed, 0xf6,
	0x63, 0x4c, 0xec, 0xa7, 0x0f, 0x27, 0xef, 0xad, 0x6a, 0xfc, 0x29, 0x26, 0xf0, 0x67, 0x60, 0x72,
	0x3a, 0x64, 0x01, 0x56, 0x9d, 0xb2, 0xcb, 0x55, 0xa3, 0xbe, 0xd6, 0xfc, 0xd6, 0xb9, 0x6f, 0xab,
	0x9c, 0xc5, 0x06, 0x3a, 0x6d, 0x4a, 0x08, 0x0e, 0x64, 0xe5, 0x97, 0x8a, 0xa7, 0x3b, 0x49, 0xb0,
	0x5b, 0xba, 0x71, 0x9f, 0xfe, 0x6a, 0xe4, 0x2c, 0xc3, 0x03, 0x7c, 0x6a, 0x85, 0xdf, 0x83, 0x8d,
	0xf4, 0xb7, 0xe6, 0x9b, 0x53, 0x7c, 0x5c, 0x73, 0xa0, 0x0e, 0xee, 0xdc, 0x6e, 0x51, 0x0b, 0x94,
	0x33, 0x4a, 0xca, 0x04, 0xb7, 0x57, 0xaa, 0xf9, 0x7a, 0xc5, 0xb5, 0x6e, 0xdc, 0xca, 0x1f, 0x06,
	0xa8, 0xcd, 0x26, 0x94, 0x16, 0x29, 0x87, 0xc3, 0xe1, 0x1e, 0x28, 0x73, 0xcc, 0x46, 0x98, 0xf9,
	0x52, 0xf0, 0xdc, 0x36, 0xab, 0xf9, 0xfa, 0xaa, 0x67, 0x6a, 0xdb, 0xb9, 0x34, 0xc1, 0x97, 0x00,
	0xce, 0x16, 0x5d, 0xf5, 0x30, 0xa0, 0xb1, 0xbd, 0xaa, 0xda, 0xff, 0xc9, 0xd4, 0xd3, 0x49, 0x1d,
	0xb0, 0x05, 0x3e, 0x43, 0x49, 0x12, 0x47, 0x41, 0xaa, 0xa2, 0xd4, 0xce, 0x6d, 0xa0, 0xa8, 0x37,
	0x6e, 0x39, 0xb3, 0x18, 0x5e, 0x7b, 0x05, 0x36, 0x96, 0x35, 0x0f, 0xae, 0x80, 0xfc, 0xd1, 0xf9,
	0x4f, 0xd6, 0x13, 0xb8, 0x09, 0x3e, 0xbd, 0x3c, 0x3a, 0x3b, 0xf1, 0xdf, 0x74, 0xfc, 0x0b, 0xcf,
	0x3f, 0xbd, 0xb8, 0xe8, 0xb8, 0x47, 0xed, 0xef, 0x2c, 0x03, 0x96, 0x41, 0xe9, 0xe4, 0x5d, 0xf7,
	0xc4, 0x3b, 0x3f, 0x3a, 0xb5, 0x72, 0x87, 0x2f, 0xe5, 0x46, 0xd4, 0xc1, 0xc1, 0x7f, 0x6d, 0xc4,
	0x6c, 0x60, 0x6f, 0x0b, 0x25, 0xc3, 0xca, 0xd5, 0xfe, 0x2e, 0x00, 0xf3, 0x96, 0x0b, 0xbe, 0x03,
	0xb0, 0xa7, 0x5e, 0xfd, 0x40, 0xbe, 0xfb, 0x03, 0x89, 0x55, 0x07, 0xc2, 0x6c, 0xbe, 0x78, 0xbc,
	0x1c, 0x3c, 0xab, 0xb7, 0xb8, 0x61, 0xbf, 0x1b, 0x60, 0xff, 0xbe, 0x83, 0x22, 0x62, 0x2e, 0x4f,
	0x80, 0xc0, 0x63, 0x91, 0x5e, 0x95, 0x4c, 0x7a, 0xb3, 0x8b, 0xeb, 0xdc, 0xb9, 0xb8, 0x8e, 0x88,
	0xb9, 0xfc, 0xf1, 0x63, 0xfa, 0x9e, 0x70, 0xc1, 0x30, 0x1a, 0x74, 0x63, 0xde, 0xd6, 0x34, 0xf2,
	0xfa, 0x78, 0xbb, 0x4b, 0x6f, 0xcf, 0x0c, 0x04, 0x0f, 0xc1, 0x8a, 0xce, 0x33, 0xdb, 0xcc, 0xea,
	0x43, 0x25, 0x7a, 0x59, 0x00, 0x74, 0xc1, 0xfa, 0x90, 0x4b, 0x09, 0xd3, 0xf1, 0x44, 0x4f, 0x3a,
	0x3d, 0x5f, 0x5b, 0x77, 0x76, 0xce, 0xa5, 0x34, 0xd6, 0x1b, 0x57, 0x19, 0x72, 0xdc, 0x91, 0x11,
	0x6a, 0xfc, 0xf0, 0x10, 0x94, 0x06, 0x58, 0xa0, 0x10, 0x09, 0x94, 0x2e, 0xec, 0xce, 0x72, 0xf5,
	0x9f, 0xa5, 0x28, 0x6f, 0x8a, 0x87, 0x1d, 0x60, 0x2d, 0x76, 0xc4, 0x2e, 0x2a, 0x8e, 0xe7, 0xcb,
	0x39, 0xba, 0x19, 0xfa, 0x52, 0x81, 0xbd, 0x75, 0x31, 0x6f, 0x80, 0x30, 0xfd, 0x1c, 0xac, 0x28,
	0x79, 0xab, 0xe7, 0xc3, 0xba, 0x14, 0xd5, 0x3e, 0xd8, 0x7b, 0x50, 0x54, 0xb5, 0x0f, 0x39, 0xb0,
	0x76, 0x9a, 0x3a, 0xfe, 0xaf, 0xdf, 0x97, 0xfc, 0xe3, 0xbf, 0x2f, 0x5f, 0xca, 0xc2, 0x0f, 0xc0,
	0x17, 0xcb, 0x0b, 0x9f, 0x2f, 0x74, 0xe1, 0x3b, 0xe3, 0xb6, 0xc1, 0x41, 0x44, 0xf5, 0x10, 0x94,
	0x3c, 0xee, 0x15, 0x95, 0xbb, 0x99, 0x11, 0xb5, 0xa7, 0x7f, 0x68, 0x94, 0x32, 0x3a, 0xc6, 0x55,
	0x51, 0x65, 0xd7, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xef, 0x93, 0xcd, 0x74, 0x0e, 0x09, 0x00,
	0x00,
}
