// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/listener/v3/listener.proto

package envoy_config_listener_v3

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	v31 "github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v3"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Listener_DrainType int32

const (
	Listener_DEFAULT     Listener_DrainType = 0
	Listener_MODIFY_ONLY Listener_DrainType = 1
)

var Listener_DrainType_name = map[int32]string{
	0: "DEFAULT",
	1: "MODIFY_ONLY",
}

var Listener_DrainType_value = map[string]int32{
	"DEFAULT":     0,
	"MODIFY_ONLY": 1,
}

func (x Listener_DrainType) String() string {
	return proto.EnumName(Listener_DrainType_name, int32(x))
}

func (Listener_DrainType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1700162847fce94e, []int{0, 0}
}

type Listener struct {
	Name                                string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address                             *v3.Address                       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FilterChains                        []*FilterChain                    `protobuf:"bytes,3,rep,name=filter_chains,json=filterChains,proto3" json:"filter_chains,omitempty"`
	HiddenEnvoyDeprecatedUseOriginalDst *wrappers.BoolValue               `protobuf:"bytes,4,opt,name=hidden_envoy_deprecated_use_original_dst,json=hiddenEnvoyDeprecatedUseOriginalDst,proto3" json:"hidden_envoy_deprecated_use_original_dst,omitempty"` // Deprecated: Do not use.
	PerConnectionBufferLimitBytes       *wrappers.UInt32Value             `protobuf:"bytes,5,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes,proto3" json:"per_connection_buffer_limit_bytes,omitempty"`
	Metadata                            *v3.Metadata                      `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DeprecatedV1                        *Listener_DeprecatedV1            `protobuf:"bytes,7,opt,name=deprecated_v1,json=deprecatedV1,proto3" json:"deprecated_v1,omitempty"`
	DrainType                           Listener_DrainType                `protobuf:"varint,8,opt,name=drain_type,json=drainType,proto3,enum=envoy.config.listener.v3.Listener_DrainType" json:"drain_type,omitempty"`
	ListenerFilters                     []*ListenerFilter                 `protobuf:"bytes,9,rep,name=listener_filters,json=listenerFilters,proto3" json:"listener_filters,omitempty"`
	ListenerFiltersTimeout              *duration.Duration                `protobuf:"bytes,15,opt,name=listener_filters_timeout,json=listenerFiltersTimeout,proto3" json:"listener_filters_timeout,omitempty"`
	ContinueOnListenerFiltersTimeout    bool                              `protobuf:"varint,17,opt,name=continue_on_listener_filters_timeout,json=continueOnListenerFiltersTimeout,proto3" json:"continue_on_listener_filters_timeout,omitempty"`
	Transparent                         *wrappers.BoolValue               `protobuf:"bytes,10,opt,name=transparent,proto3" json:"transparent,omitempty"`
	Freebind                            *wrappers.BoolValue               `protobuf:"bytes,11,opt,name=freebind,proto3" json:"freebind,omitempty"`
	SocketOptions                       []*v3.SocketOption                `protobuf:"bytes,13,rep,name=socket_options,json=socketOptions,proto3" json:"socket_options,omitempty"`
	TcpFastOpenQueueLength              *wrappers.UInt32Value             `protobuf:"bytes,12,opt,name=tcp_fast_open_queue_length,json=tcpFastOpenQueueLength,proto3" json:"tcp_fast_open_queue_length,omitempty"`
	TrafficDirection                    v3.TrafficDirection               `protobuf:"varint,16,opt,name=traffic_direction,json=trafficDirection,proto3,enum=envoy.config.core.v3.TrafficDirection" json:"traffic_direction,omitempty"`
	UdpListenerConfig                   *UdpListenerConfig                `protobuf:"bytes,18,opt,name=udp_listener_config,json=udpListenerConfig,proto3" json:"udp_listener_config,omitempty"`
	ApiListener                         *ApiListener                      `protobuf:"bytes,19,opt,name=api_listener,json=apiListener,proto3" json:"api_listener,omitempty"`
	ConnectionBalanceConfig             *Listener_ConnectionBalanceConfig `protobuf:"bytes,20,opt,name=connection_balance_config,json=connectionBalanceConfig,proto3" json:"connection_balance_config,omitempty"`
	ReusePort                           bool                              `protobuf:"varint,21,opt,name=reuse_port,json=reusePort,proto3" json:"reuse_port,omitempty"`
	AccessLog                           []*v31.AccessLog                  `protobuf:"bytes,22,rep,name=access_log,json=accessLog,proto3" json:"access_log,omitempty"`
	XXX_NoUnkeyedLiteral                struct{}                          `json:"-"`
	XXX_unrecognized                    []byte                            `json:"-"`
	XXX_sizecache                       int32                             `json:"-"`
}

func (m *Listener) Reset()         { *m = Listener{} }
func (m *Listener) String() string { return proto.CompactTextString(m) }
func (*Listener) ProtoMessage()    {}
func (*Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_1700162847fce94e, []int{0}
}

func (m *Listener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener.Unmarshal(m, b)
}
func (m *Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener.Marshal(b, m, deterministic)
}
func (m *Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener.Merge(m, src)
}
func (m *Listener) XXX_Size() int {
	return xxx_messageInfo_Listener.Size(m)
}
func (m *Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_Listener proto.InternalMessageInfo

func (m *Listener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listener) GetAddress() *v3.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Listener) GetFilterChains() []*FilterChain {
	if m != nil {
		return m.FilterChains
	}
	return nil
}

// Deprecated: Do not use.
func (m *Listener) GetHiddenEnvoyDeprecatedUseOriginalDst() *wrappers.BoolValue {
	if m != nil {
		return m.HiddenEnvoyDeprecatedUseOriginalDst
	}
	return nil
}

func (m *Listener) GetPerConnectionBufferLimitBytes() *wrappers.UInt32Value {
	if m != nil {
		return m.PerConnectionBufferLimitBytes
	}
	return nil
}

func (m *Listener) GetMetadata() *v3.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Listener) GetDeprecatedV1() *Listener_DeprecatedV1 {
	if m != nil {
		return m.DeprecatedV1
	}
	return nil
}

func (m *Listener) GetDrainType() Listener_DrainType {
	if m != nil {
		return m.DrainType
	}
	return Listener_DEFAULT
}

func (m *Listener) GetListenerFilters() []*ListenerFilter {
	if m != nil {
		return m.ListenerFilters
	}
	return nil
}

func (m *Listener) GetListenerFiltersTimeout() *duration.Duration {
	if m != nil {
		return m.ListenerFiltersTimeout
	}
	return nil
}

func (m *Listener) GetContinueOnListenerFiltersTimeout() bool {
	if m != nil {
		return m.ContinueOnListenerFiltersTimeout
	}
	return false
}

func (m *Listener) GetTransparent() *wrappers.BoolValue {
	if m != nil {
		return m.Transparent
	}
	return nil
}

func (m *Listener) GetFreebind() *wrappers.BoolValue {
	if m != nil {
		return m.Freebind
	}
	return nil
}

func (m *Listener) GetSocketOptions() []*v3.SocketOption {
	if m != nil {
		return m.SocketOptions
	}
	return nil
}

func (m *Listener) GetTcpFastOpenQueueLength() *wrappers.UInt32Value {
	if m != nil {
		return m.TcpFastOpenQueueLength
	}
	return nil
}

func (m *Listener) GetTrafficDirection() v3.TrafficDirection {
	if m != nil {
		return m.TrafficDirection
	}
	return v3.TrafficDirection_UNSPECIFIED
}

func (m *Listener) GetUdpListenerConfig() *UdpListenerConfig {
	if m != nil {
		return m.UdpListenerConfig
	}
	return nil
}

func (m *Listener) GetApiListener() *ApiListener {
	if m != nil {
		return m.ApiListener
	}
	return nil
}

func (m *Listener) GetConnectionBalanceConfig() *Listener_ConnectionBalanceConfig {
	if m != nil {
		return m.ConnectionBalanceConfig
	}
	return nil
}

func (m *Listener) GetReusePort() bool {
	if m != nil {
		return m.ReusePort
	}
	return false
}

func (m *Listener) GetAccessLog() []*v31.AccessLog {
	if m != nil {
		return m.AccessLog
	}
	return nil
}

type Listener_DeprecatedV1 struct {
	BindToPort           *wrappers.BoolValue `protobuf:"bytes,1,opt,name=bind_to_port,json=bindToPort,proto3" json:"bind_to_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Listener_DeprecatedV1) Reset()         { *m = Listener_DeprecatedV1{} }
func (m *Listener_DeprecatedV1) String() string { return proto.CompactTextString(m) }
func (*Listener_DeprecatedV1) ProtoMessage()    {}
func (*Listener_DeprecatedV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_1700162847fce94e, []int{0, 0}
}

func (m *Listener_DeprecatedV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener_DeprecatedV1.Unmarshal(m, b)
}
func (m *Listener_DeprecatedV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener_DeprecatedV1.Marshal(b, m, deterministic)
}
func (m *Listener_DeprecatedV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener_DeprecatedV1.Merge(m, src)
}
func (m *Listener_DeprecatedV1) XXX_Size() int {
	return xxx_messageInfo_Listener_DeprecatedV1.Size(m)
}
func (m *Listener_DeprecatedV1) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener_DeprecatedV1.DiscardUnknown(m)
}

var xxx_messageInfo_Listener_DeprecatedV1 proto.InternalMessageInfo

func (m *Listener_DeprecatedV1) GetBindToPort() *wrappers.BoolValue {
	if m != nil {
		return m.BindToPort
	}
	return nil
}

type Listener_ConnectionBalanceConfig struct {
	// Types that are valid to be assigned to BalanceType:
	//	*Listener_ConnectionBalanceConfig_ExactBalance_
	BalanceType          isListener_ConnectionBalanceConfig_BalanceType `protobuf_oneof:"balance_type"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Listener_ConnectionBalanceConfig) Reset()         { *m = Listener_ConnectionBalanceConfig{} }
func (m *Listener_ConnectionBalanceConfig) String() string { return proto.CompactTextString(m) }
func (*Listener_ConnectionBalanceConfig) ProtoMessage()    {}
func (*Listener_ConnectionBalanceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1700162847fce94e, []int{0, 1}
}

func (m *Listener_ConnectionBalanceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig.Unmarshal(m, b)
}
func (m *Listener_ConnectionBalanceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig.Marshal(b, m, deterministic)
}
func (m *Listener_ConnectionBalanceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener_ConnectionBalanceConfig.Merge(m, src)
}
func (m *Listener_ConnectionBalanceConfig) XXX_Size() int {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig.Size(m)
}
func (m *Listener_ConnectionBalanceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener_ConnectionBalanceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Listener_ConnectionBalanceConfig proto.InternalMessageInfo

type isListener_ConnectionBalanceConfig_BalanceType interface {
	isListener_ConnectionBalanceConfig_BalanceType()
}

type Listener_ConnectionBalanceConfig_ExactBalance_ struct {
	ExactBalance *Listener_ConnectionBalanceConfig_ExactBalance `protobuf:"bytes,1,opt,name=exact_balance,json=exactBalance,proto3,oneof"`
}

func (*Listener_ConnectionBalanceConfig_ExactBalance_) isListener_ConnectionBalanceConfig_BalanceType() {
}

func (m *Listener_ConnectionBalanceConfig) GetBalanceType() isListener_ConnectionBalanceConfig_BalanceType {
	if m != nil {
		return m.BalanceType
	}
	return nil
}

func (m *Listener_ConnectionBalanceConfig) GetExactBalance() *Listener_ConnectionBalanceConfig_ExactBalance {
	if x, ok := m.GetBalanceType().(*Listener_ConnectionBalanceConfig_ExactBalance_); ok {
		return x.ExactBalance
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Listener_ConnectionBalanceConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Listener_ConnectionBalanceConfig_ExactBalance_)(nil),
	}
}

type Listener_ConnectionBalanceConfig_ExactBalance struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listener_ConnectionBalanceConfig_ExactBalance) Reset() {
	*m = Listener_ConnectionBalanceConfig_ExactBalance{}
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) String() string {
	return proto.CompactTextString(m)
}
func (*Listener_ConnectionBalanceConfig_ExactBalance) ProtoMessage() {}
func (*Listener_ConnectionBalanceConfig_ExactBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_1700162847fce94e, []int{0, 1, 0}
}

func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Unmarshal(m, b)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Marshal(b, m, deterministic)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Merge(m, src)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Size() int {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Size(m)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.DiscardUnknown(m)
}

var xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("envoy.config.listener.v3.Listener_DrainType", Listener_DrainType_name, Listener_DrainType_value)
	proto.RegisterType((*Listener)(nil), "envoy.config.listener.v3.Listener")
	proto.RegisterType((*Listener_DeprecatedV1)(nil), "envoy.config.listener.v3.Listener.DeprecatedV1")
	proto.RegisterType((*Listener_ConnectionBalanceConfig)(nil), "envoy.config.listener.v3.Listener.ConnectionBalanceConfig")
	proto.RegisterType((*Listener_ConnectionBalanceConfig_ExactBalance)(nil), "envoy.config.listener.v3.Listener.ConnectionBalanceConfig.ExactBalance")
}

func init() {
	proto.RegisterFile("envoy/config/listener/v3/listener.proto", fileDescriptor_1700162847fce94e)
}

var fileDescriptor_1700162847fce94e = []byte{
	// 1074 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x52, 0x1b, 0x37,
	0x14, 0xce, 0x92, 0x1f, 0x6c, 0xd9, 0x06, 0x23, 0x1a, 0xd8, 0x78, 0x80, 0x3a, 0x94, 0xa6, 0x66,
	0xd2, 0xae, 0x27, 0xa6, 0xd3, 0x99, 0x7a, 0xb8, 0xc1, 0x18, 0x1a, 0x52, 0x27, 0x26, 0x8b, 0xc9,
	0x34, 0xd3, 0x0b, 0x8d, 0xbc, 0x2b, 0x1b, 0x4d, 0x17, 0x69, 0x2b, 0x69, 0x9d, 0xf0, 0x06, 0x9d,
	0x3e, 0x42, 0x5f, 0xa0, 0x4f, 0xd2, 0x9b, 0x3e, 0x51, 0xa7, 0x57, 0x1d, 0x69, 0x77, 0xcd, 0x1a,
	0xec, 0x9a, 0xf6, 0x4e, 0x47, 0xfa, 0xce, 0x77, 0x8e, 0xbe, 0x73, 0x74, 0x76, 0xc1, 0x17, 0x84,
	0x8d, 0xf8, 0x55, 0xdd, 0xe3, 0x6c, 0x40, 0x87, 0xf5, 0x80, 0x4a, 0x45, 0x18, 0x11, 0xf5, 0xd1,
	0xde, 0x78, 0xed, 0x84, 0x82, 0x2b, 0x0e, 0x6d, 0x03, 0x74, 0x62, 0xa0, 0x33, 0x3e, 0x1c, 0xed,
	0x55, 0x76, 0x27, 0x28, 0xb0, 0xe7, 0x11, 0x29, 0x03, 0x3e, 0xd4, 0x1c, 0x63, 0x23, 0x26, 0xa9,
	0x6c, 0x4f, 0x40, 0x3d, 0x2e, 0x88, 0x41, 0xf9, 0xbe, 0x20, 0x52, 0x26, 0x98, 0x4f, 0xa7, 0x62,
	0xfa, 0x58, 0x92, 0x04, 0x50, 0x9b, 0x0a, 0x90, 0xdc, 0xfb, 0x89, 0x28, 0xc4, 0x43, 0x45, 0x39,
	0x4b, 0x90, 0xcf, 0x67, 0x5e, 0x0e, 0x87, 0x14, 0x4d, 0x5e, 0xb0, 0xd2, 0x98, 0xab, 0x04, 0xf2,
	0xf8, 0x65, 0xc8, 0x19, 0x61, 0x4a, 0xce, 0xf5, 0x89, 0xfc, 0x10, 0x65, 0xfc, 0x8c, 0x68, 0xb1,
	0xcf, 0xc6, 0x90, 0xf3, 0x61, 0x40, 0x74, 0x0a, 0x75, 0xcc, 0x18, 0x57, 0x58, 0x67, 0x9c, 0x32,
	0x6e, 0x25, 0xa7, 0xc6, 0xea, 0x47, 0x83, 0xba, 0x1f, 0x09, 0x9c, 0xb9, 0xd2, 0xad, 0xf3, 0x0f,
	0x02, 0x87, 0x21, 0x11, 0xa9, 0xff, 0xd3, 0xc8, 0x0f, 0x71, 0x96, 0xb7, 0x3e, 0x22, 0x42, 0x52,
	0xce, 0x28, 0x4b, 0x13, 0x58, 0x1f, 0xe1, 0x80, 0xfa, 0x58, 0x91, 0x7a, 0xba, 0x88, 0x0f, 0xb6,
	0xff, 0x2c, 0x83, 0x5c, 0x27, 0xc9, 0x19, 0x42, 0xf0, 0x80, 0xe1, 0x4b, 0x62, 0x5b, 0x55, 0xab,
	0x96, 0x77, 0xcd, 0x1a, 0x1e, 0x80, 0xc5, 0xa4, 0x56, 0xf6, 0x42, 0xd5, 0xaa, 0x15, 0x1a, 0x9b,
	0xce, 0x44, 0x57, 0xe8, 0x5a, 0x38, 0xa3, 0x3d, 0xe7, 0x20, 0x06, 0xb5, 0x72, 0x7f, 0xb7, 0x1e,
	0xfe, 0x6a, 0x2d, 0x94, 0x2d, 0x37, 0xf5, 0x83, 0xaf, 0x40, 0x69, 0x40, 0x03, 0xa5, 0x45, 0xb9,
	0xc0, 0x94, 0x49, 0xfb, 0x7e, 0xf5, 0x7e, 0xad, 0xd0, 0xf8, 0xdc, 0x99, 0xd5, 0x5e, 0xce, 0xb1,
	0x81, 0x1f, 0x6a, 0xb4, 0x5b, 0x1c, 0x5c, 0x1b, 0x12, 0x46, 0xa0, 0x76, 0x41, 0x7d, 0x9f, 0x30,
	0x64, 0x9c, 0x91, 0x4f, 0x42, 0x41, 0x3c, 0xac, 0x88, 0x8f, 0x22, 0x49, 0x10, 0x17, 0x74, 0x48,
	0x19, 0x0e, 0x90, 0x2f, 0x95, 0xfd, 0xc0, 0xe4, 0x5b, 0x71, 0x62, 0xf9, 0x9c, 0x54, 0x3e, 0xa7,
	0xc5, 0x79, 0xf0, 0x0e, 0x07, 0x11, 0x69, 0x2d, 0xd8, 0x96, 0xfb, 0x59, 0xcc, 0x77, 0xa4, 0xe9,
	0xda, 0x63, 0xb6, 0x73, 0x49, 0xba, 0x09, 0x57, 0x5b, 0x2a, 0x38, 0x00, 0x4f, 0xc3, 0xb8, 0xa8,
	0x8c, 0x78, 0x5a, 0x63, 0xd4, 0x8f, 0x06, 0x03, 0x22, 0x50, 0x40, 0x2f, 0xa9, 0x42, 0xfd, 0x2b,
	0x45, 0xa4, 0xfd, 0xd0, 0xc4, 0xdb, 0xb8, 0x15, 0xef, 0xfc, 0x84, 0xa9, 0xbd, 0x86, 0x89, 0xe8,
	0x6e, 0x86, 0x44, 0x1c, 0x8e, 0x59, 0x5a, 0x86, 0xa4, 0xa3, 0x39, 0x5a, 0x9a, 0x02, 0x36, 0x41,
	0xee, 0x92, 0x28, 0xec, 0x63, 0x85, 0xed, 0x47, 0x86, 0x6e, 0x6b, 0xba, 0xdc, 0xaf, 0x13, 0x94,
	0x3b, 0xc6, 0xc3, 0x1e, 0x28, 0x65, 0xd4, 0x18, 0xbd, 0xb0, 0x17, 0x0d, 0x41, 0x7d, 0xb6, 0xcc,
	0x69, 0xe1, 0x9d, 0xeb, 0x7b, 0xbf, 0x7b, 0xe1, 0x16, 0xfd, 0x8c, 0x05, 0xbf, 0x07, 0xc0, 0x17,
	0x98, 0x32, 0xa4, 0xae, 0x42, 0x62, 0xe7, 0xaa, 0x56, 0x6d, 0xa9, 0xf1, 0xe5, 0x5d, 0x28, 0xb5,
	0x53, 0xef, 0x2a, 0x24, 0x6e, 0xde, 0x4f, 0x97, 0xf0, 0x0c, 0x94, 0xc7, 0x0f, 0x24, 0x2e, 0xab,
	0xb4, 0xf3, 0xa6, 0x19, 0x6a, 0xf3, 0x29, 0xe3, 0xa6, 0x70, 0x97, 0x83, 0x09, 0x5b, 0xc2, 0x33,
	0x60, 0xdf, 0x24, 0x45, 0x8a, 0x5e, 0x12, 0x1e, 0x29, 0x7b, 0xd9, 0x48, 0xf0, 0xe4, 0x56, 0x49,
	0xda, 0xc9, 0x0b, 0x73, 0xd7, 0x6e, 0xb0, 0xf5, 0x62, 0x47, 0xf8, 0x06, 0xec, 0x78, 0x9c, 0x29,
	0xca, 0x22, 0x82, 0x38, 0x43, 0x33, 0x03, 0xac, 0x54, 0xad, 0x5a, 0xce, 0xad, 0xa6, 0xd8, 0x2e,
	0xeb, 0x4c, 0xe7, 0xdb, 0x07, 0x05, 0x25, 0x30, 0x93, 0x21, 0x16, 0x84, 0x29, 0x1b, 0xcc, 0x6b,
	0x4d, 0x37, 0x0b, 0x87, 0xdf, 0x80, 0xdc, 0x40, 0x10, 0xd2, 0xa7, 0xcc, 0xb7, 0x0b, 0x73, 0x5d,
	0xc7, 0x58, 0x78, 0x02, 0x96, 0x26, 0x66, 0xa4, 0xb4, 0x4b, 0x46, 0xed, 0xed, 0xe9, 0x4d, 0x75,
	0x66, 0xb0, 0x5d, 0x03, 0x75, 0x4b, 0x32, 0x63, 0x49, 0xf8, 0x03, 0xa8, 0x28, 0x2f, 0x44, 0x03,
	0x2c, 0x35, 0x19, 0x61, 0xe8, 0xe7, 0x88, 0x44, 0x04, 0x05, 0x84, 0x0d, 0xd5, 0x85, 0x5d, 0xbc,
	0x43, 0xeb, 0xaf, 0x29, 0x2f, 0x3c, 0xc6, 0x52, 0x75, 0x43, 0xc2, 0xde, 0x6a, 0xe7, 0x8e, 0xf1,
	0x85, 0x67, 0x60, 0x45, 0x09, 0x3c, 0x18, 0x50, 0x0f, 0xf9, 0x54, 0xc4, 0x0f, 0xc3, 0x2e, 0x9b,
	0x46, 0x7b, 0x36, 0x3d, 0xcf, 0x5e, 0x0c, 0x6f, 0xa7, 0x68, 0xb7, 0xac, 0x6e, 0xec, 0xc0, 0x1f,
	0xc1, 0xea, 0x94, 0x71, 0x6c, 0x43, 0x93, 0xe7, 0xf3, 0xd9, 0xcd, 0x76, 0xee, 0x87, 0x69, 0x05,
	0x0f, 0xcd, 0xa9, 0xbb, 0x12, 0xdd, 0xdc, 0x82, 0x2f, 0x41, 0x31, 0xfb, 0x31, 0xb1, 0x57, 0x0d,
	0xeb, 0xbf, 0xcc, 0xb3, 0x83, 0x90, 0xa6, 0x14, 0x6e, 0x01, 0x5f, 0x1b, 0x70, 0x04, 0x9e, 0x64,
	0x67, 0x0a, 0x0e, 0x30, 0xf3, 0x48, 0x9a, 0xec, 0x27, 0x86, 0xb6, 0x79, 0x87, 0xc7, 0x96, 0x99,
	0x28, 0x31, 0x45, 0x92, 0xfb, 0xba, 0x37, 0xfd, 0x00, 0x6e, 0x02, 0x20, 0x88, 0x1e, 0x98, 0x21,
	0x17, 0xca, 0x7e, 0x6c, 0x9a, 0x38, 0x6f, 0x76, 0x4e, 0xb9, 0x50, 0xf0, 0x10, 0x80, 0xf8, 0x33,
	0x8e, 0x02, 0x3e, 0xb4, 0xd7, 0x4c, 0xcf, 0xec, 0x4c, 0xe6, 0x71, 0xfd, 0x99, 0xd7, 0xf7, 0x33,
	0x46, 0x87, 0x0f, 0xdd, 0x3c, 0x4e, 0x97, 0x95, 0x0f, 0xa0, 0x98, 0x9d, 0x2b, 0x70, 0x1f, 0x14,
	0x75, 0x53, 0x22, 0xc5, 0xe3, 0xa8, 0xd6, 0xdc, 0x46, 0x06, 0x1a, 0xdf, 0xe3, 0x3a, 0xa5, 0xe6,
	0xee, 0x6f, 0x7f, 0xfc, 0xb2, 0xb5, 0x03, 0xe2, 0xbf, 0x09, 0x07, 0x87, 0xd4, 0x19, 0x35, 0xa6,
	0x0f, 0xb0, 0xca, 0xef, 0x0b, 0x60, 0x7d, 0x86, 0x22, 0x90, 0x81, 0x12, 0xf9, 0x88, 0x3d, 0x95,
	0x6a, 0x9d, 0x64, 0xf1, 0xdd, 0xff, 0x17, 0xd9, 0x39, 0xd2, 0x7c, 0xc9, 0xd6, 0xcb, 0x7b, 0x6e,
	0x91, 0x64, 0xec, 0xca, 0x5b, 0x50, 0xcc, 0x9e, 0x37, 0x0f, 0xf4, 0x35, 0xf6, 0x41, 0x73, 0xfa,
	0x35, 0xee, 0x12, 0xa2, 0xf9, 0xb5, 0xa6, 0xa8, 0x83, 0xaf, 0xfe, 0x13, 0x45, 0x6b, 0x15, 0x14,
	0xd3, 0xf6, 0xd2, 0x93, 0x1c, 0xde, 0xff, 0xab, 0x65, 0x6d, 0xef, 0x82, 0xfc, 0x78, 0x4e, 0xc3,
	0x02, 0x58, 0x6c, 0x1f, 0x1d, 0x1f, 0x9c, 0x77, 0x7a, 0xe5, 0x7b, 0x70, 0x19, 0x14, 0x5e, 0x77,
	0xdb, 0x27, 0xc7, 0xef, 0x51, 0xf7, 0x4d, 0xe7, 0x7d, 0xd9, 0x6a, 0x6e, 0xe8, 0xa8, 0xeb, 0xe0,
	0xf1, 0xd4, 0xa8, 0xaf, 0x1e, 0xe4, 0x96, 0xca, 0xcb, 0xad, 0x6f, 0xc1, 0x33, 0xca, 0x63, 0x25,
	0x43, 0xc1, 0x3f, 0x5e, 0xcd, 0x14, 0xb5, 0x55, 0x4a, 0x3d, 0x4f, 0x75, 0xd5, 0x4f, 0xad, 0xfe,
	0x23, 0x53, 0xfe, 0xbd, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0x61, 0x7b, 0x7d, 0x9c, 0x0a,
	0x00, 0x00,
}
