// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/type/matcher/v3/regex.proto

package envoy_type_matcher_v3

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegexMatcher struct {
	// Types that are valid to be assigned to EngineType:
	//	*RegexMatcher_GoogleRe2
	EngineType           isRegexMatcher_EngineType `protobuf_oneof:"engine_type"`
	Regex                string                    `protobuf:"bytes,2,opt,name=regex,proto3" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RegexMatcher) Reset()         { *m = RegexMatcher{} }
func (m *RegexMatcher) String() string { return proto.CompactTextString(m) }
func (*RegexMatcher) ProtoMessage()    {}
func (*RegexMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_7de4f215ebc85482, []int{0}
}

func (m *RegexMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegexMatcher.Unmarshal(m, b)
}
func (m *RegexMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegexMatcher.Marshal(b, m, deterministic)
}
func (m *RegexMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegexMatcher.Merge(m, src)
}
func (m *RegexMatcher) XXX_Size() int {
	return xxx_messageInfo_RegexMatcher.Size(m)
}
func (m *RegexMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_RegexMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_RegexMatcher proto.InternalMessageInfo

type isRegexMatcher_EngineType interface {
	isRegexMatcher_EngineType()
}

type RegexMatcher_GoogleRe2 struct {
	GoogleRe2 *RegexMatcher_GoogleRE2 `protobuf:"bytes,1,opt,name=google_re2,json=googleRe2,proto3,oneof"`
}

func (*RegexMatcher_GoogleRe2) isRegexMatcher_EngineType() {}

func (m *RegexMatcher) GetEngineType() isRegexMatcher_EngineType {
	if m != nil {
		return m.EngineType
	}
	return nil
}

func (m *RegexMatcher) GetGoogleRe2() *RegexMatcher_GoogleRE2 {
	if x, ok := m.GetEngineType().(*RegexMatcher_GoogleRe2); ok {
		return x.GoogleRe2
	}
	return nil
}

func (m *RegexMatcher) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RegexMatcher) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RegexMatcher_GoogleRe2)(nil),
	}
}

type RegexMatcher_GoogleRE2 struct {
	MaxProgramSize       *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=max_program_size,json=maxProgramSize,proto3" json:"max_program_size,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegexMatcher_GoogleRE2) Reset()         { *m = RegexMatcher_GoogleRE2{} }
func (m *RegexMatcher_GoogleRE2) String() string { return proto.CompactTextString(m) }
func (*RegexMatcher_GoogleRE2) ProtoMessage()    {}
func (*RegexMatcher_GoogleRE2) Descriptor() ([]byte, []int) {
	return fileDescriptor_7de4f215ebc85482, []int{0, 0}
}

func (m *RegexMatcher_GoogleRE2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegexMatcher_GoogleRE2.Unmarshal(m, b)
}
func (m *RegexMatcher_GoogleRE2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegexMatcher_GoogleRE2.Marshal(b, m, deterministic)
}
func (m *RegexMatcher_GoogleRE2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegexMatcher_GoogleRE2.Merge(m, src)
}
func (m *RegexMatcher_GoogleRE2) XXX_Size() int {
	return xxx_messageInfo_RegexMatcher_GoogleRE2.Size(m)
}
func (m *RegexMatcher_GoogleRE2) XXX_DiscardUnknown() {
	xxx_messageInfo_RegexMatcher_GoogleRE2.DiscardUnknown(m)
}

var xxx_messageInfo_RegexMatcher_GoogleRE2 proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *RegexMatcher_GoogleRE2) GetMaxProgramSize() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxProgramSize
	}
	return nil
}

type RegexMatchAndSubstitute struct {
	Pattern              *RegexMatcher `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Substitution         string        `protobuf:"bytes,2,opt,name=substitution,proto3" json:"substitution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegexMatchAndSubstitute) Reset()         { *m = RegexMatchAndSubstitute{} }
func (m *RegexMatchAndSubstitute) String() string { return proto.CompactTextString(m) }
func (*RegexMatchAndSubstitute) ProtoMessage()    {}
func (*RegexMatchAndSubstitute) Descriptor() ([]byte, []int) {
	return fileDescriptor_7de4f215ebc85482, []int{1}
}

func (m *RegexMatchAndSubstitute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegexMatchAndSubstitute.Unmarshal(m, b)
}
func (m *RegexMatchAndSubstitute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegexMatchAndSubstitute.Marshal(b, m, deterministic)
}
func (m *RegexMatchAndSubstitute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegexMatchAndSubstitute.Merge(m, src)
}
func (m *RegexMatchAndSubstitute) XXX_Size() int {
	return xxx_messageInfo_RegexMatchAndSubstitute.Size(m)
}
func (m *RegexMatchAndSubstitute) XXX_DiscardUnknown() {
	xxx_messageInfo_RegexMatchAndSubstitute.DiscardUnknown(m)
}

var xxx_messageInfo_RegexMatchAndSubstitute proto.InternalMessageInfo

func (m *RegexMatchAndSubstitute) GetPattern() *RegexMatcher {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *RegexMatchAndSubstitute) GetSubstitution() string {
	if m != nil {
		return m.Substitution
	}
	return ""
}

func init() {
	proto.RegisterType((*RegexMatcher)(nil), "envoy.type.matcher.v3.RegexMatcher")
	proto.RegisterType((*RegexMatcher_GoogleRE2)(nil), "envoy.type.matcher.v3.RegexMatcher.GoogleRE2")
	proto.RegisterType((*RegexMatchAndSubstitute)(nil), "envoy.type.matcher.v3.RegexMatchAndSubstitute")
}

func init() { proto.RegisterFile("envoy/type/matcher/v3/regex.proto", fileDescriptor_7de4f215ebc85482) }

var fileDescriptor_7de4f215ebc85482 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x9d, 0xd5, 0xb6, 0xe6, 0x6d, 0x91, 0xb0, 0x20, 0x0d, 0xc1, 0xd6, 0x24, 0x05, 0xa9,
	0xff, 0x66, 0x74, 0x73, 0x8b, 0x27, 0x07, 0xa4, 0x2a, 0x08, 0x61, 0x8a, 0xe2, 0x2d, 0x4c, 0xcc,
	0xeb, 0x3a, 0x90, 0xcc, 0x0c, 0xb3, 0xb3, 0x6b, 0xd2, 0x93, 0x47, 0xf5, 0x23, 0xf8, 0x4d, 0xf4,
	0x2e, 0x78, 0x13, 0xbf, 0x8d, 0xf4, 0x24, 0xbb, 0x93, 0xb5, 0x06, 0x83, 0xf6, 0xb6, 0xec, 0xfb,
	0x3c, 0x0f, 0xbf, 0xe7, 0x19, 0xe8, 0xa2, 0x2e, 0xcc, 0x82, 0xf9, 0x85, 0x45, 0x36, 0x93, 0xfe,
	0xd5, 0x1b, 0x74, 0xac, 0xe8, 0x33, 0x87, 0x29, 0xce, 0xa9, 0x75, 0xc6, 0x9b, 0xf8, 0x6a, 0x25,
	0xa1, 0xa5, 0x84, 0x2e, 0x25, 0xb4, 0xe8, 0xb7, 0xf7, 0x53, 0x63, 0xd2, 0x29, 0xb2, 0x4a, 0x34,
	0xce, 0x5f, 0xb3, 0xb7, 0x4e, 0x5a, 0x8b, 0x2e, 0x0b, 0xb6, 0xf6, 0x5e, 0x3e, 0xb1, 0x92, 0x49,
	0xad, 0x8d, 0x97, 0x5e, 0x19, 0x9d, 0xb1, 0xcc, 0x4b, 0x9f, 0xd7, 0xe7, 0xee, 0x5f, 0xe7, 0x02,
	0x5d, 0xa6, 0x8c, 0x56, 0x3a, 0x5d, 0x4a, 0x76, 0x0b, 0x39, 0x55, 0x13, 0xe9, 0x91, 0xd5, 0x1f,
	0xe1, 0xd0, 0xfb, 0x1e, 0xc1, 0x8e, 0x28, 0x09, 0x9f, 0x05, 0x9c, 0xf8, 0x25, 0x40, 0xa0, 0x19,
	0x39, 0x4c, 0x5a, 0xa4, 0x43, 0x0e, 0xb7, 0x93, 0xbb, 0x74, 0x2d, 0x37, 0xfd, 0xd3, 0x48, 0x8f,
	0x2a, 0x97, 0x78, 0x94, 0xf0, 0xcb, 0xa7, 0x7c, 0xe3, 0x23, 0x89, 0x9a, 0xe4, 0xf1, 0x05, 0xd1,
	0x08, 0x61, 0x02, 0x93, 0x78, 0x0f, 0x36, 0xaa, 0x2d, 0x5a, 0x51, 0x87, 0x1c, 0x36, 0xf8, 0xd6,
	0x29, 0xbf, 0xe4, 0xa2, 0x0e, 0x11, 0xe1, 0x6f, 0xfb, 0x03, 0x81, 0xc6, 0xef, 0x8c, 0xf8, 0x29,
	0x34, 0x67, 0x72, 0x3e, 0xb2, 0xce, 0xa4, 0x4e, 0xce, 0x46, 0x99, 0x3a, 0xc1, 0x25, 0xcc, 0x35,
	0x1a, 0x22, 0x69, 0xbd, 0x16, 0x7d, 0xfe, 0x44, 0xfb, 0x7e, 0xf2, 0x42, 0x4e, 0x73, 0xe4, 0x51,
	0x8b, 0x88, 0x2b, 0x33, 0x39, 0x1f, 0x06, 0xe3, 0xb1, 0x3a, 0xc1, 0xc1, 0xbd, 0x4f, 0x5f, 0xdf,
	0xef, 0xdf, 0x86, 0x9b, 0x6b, 0x4a, 0xac, 0x6f, 0x30, 0xb8, 0x51, 0x3a, 0xba, 0x70, 0xfd, 0x3f,
	0x0e, 0x1e, 0xc3, 0x36, 0xea, 0x54, 0x69, 0x1c, 0x95, 0x9a, 0xf8, 0xe2, 0x4f, 0x4e, 0x7a, 0x9f,
	0x09, 0xec, 0x9e, 0x89, 0x1e, 0xea, 0xc9, 0x71, 0x3e, 0xce, 0xbc, 0xf2, 0xb9, 0xc7, 0xf8, 0x08,
	0xb6, 0xac, 0xf4, 0x1e, 0x9d, 0x5e, 0x96, 0x39, 0x38, 0xc7, 0xb2, 0x67, 0x7b, 0x8a, 0xda, 0x1d,
	0xf7, 0x60, 0x27, 0xab, 0x63, 0x95, 0xd1, 0x61, 0x52, 0xb1, 0xf2, 0x6f, 0x70, 0xbf, 0x2c, 0x71,
	0x07, 0x6e, 0xfd, 0xb3, 0xc4, 0x0a, 0x1f, 0x7f, 0xf0, 0xe5, 0xdd, 0xb7, 0x1f, 0x9b, 0x51, 0x33,
	0x82, 0x03, 0x65, 0x02, 0x9a, 0x75, 0x66, 0xbe, 0x58, 0x4f, 0xc9, 0xa1, 0xca, 0x19, 0x96, 0xef,
	0x30, 0x24, 0xe3, 0xcd, 0xea, 0x41, 0xfa, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78, 0xdb, 0x81,
	0x23, 0x08, 0x03, 0x00, 0x00,
}
