formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/envoyproxy/go-control-plane
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - bodyclose
    - contextcheck
    - errorlint
    - gosec
    - misspell
    - perfsprint
    - revive
    - testifylint
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: pkg/test/resource/v3/secret.go
        text: G101
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G115
    misspell:
      locale: US
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    revive:
      enable-default-rules: true
    testifylint:
      disable:
        - float-compare
        - go-require
      enable-all: true
    unparam:
      check-exported: false
version: "2"
