run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - gofmt
  - goimports
  - gosec
  - misspell
  - revive
  - unconvert
  - unparam

linters-settings:
  misspell:
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  goimports:
    local-prefixes: github.com/envoyproxy/go-control-plane

issues:
  fix: true
