issues:
  fix: true
  exclude-rules:
    - linters:
        - gosec
      text: 'G101'
      path: 'pkg/test/resource/v3/secret.go'
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errorlint
    - gofumpt
    - goimports
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/envoyproxy/go-control-plane
  misspell:
    locale: US
  unparam:
    check-exported: false

run:
  timeout: 10m
