formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/envoyproxy/go-control-plane
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - bodyclose
    - contextcheck
    - errorlint
    - gocritic
    - godot
    - gosec
    - misspell
    - modernize
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: pkg/test/resource/v3/secret.go
        text: G101
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - appendAssign
    gosec:
      excludes:
        - G115
    misspell:
      locale: US
    nolintlint:
      require-specific: true
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    revive:
      enable-default-rules: true
      rules:
        - name: var-naming
          arguments:
            - ["ID"] # AllowList
            - ["VM"] # DenyList
            - - skip-initialism-name-checks: true
                upper-case-const: true
                skip-package-name-checks: true
                skip-package-name-collision-with-go-std: true
    staticcheck:
      checks:
        - all
        - -ST1003
    testifylint:
      disable:
        - float-compare
        - go-require
      enable-all: true
    unparam:
      check-exported: false
version: "2"
