issues:
  fix: true
  exclude-rules:
    - linters:
      - gosec
      text: 'G101'
      path: 'pkg/test/resource/v3/secret.go'
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  presets:
  - bugs

  enable:
  - bodyclose
  - errorlint
  - gofumpt
  - goimports
  - gosec
  - misspell
  - revive
  - unconvert
  - unparam

  disable:
  - scopelint # deprecated but still enabled in the bugs preset

linters-settings:
  misspell:
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  goimports:
    local-prefixes: github.com/envoyproxy/go-control-plane
  exhaustive:
    default-signifies-exhaustive: true

run:
  timeout: 10m
