FROM golang:1.14.6-stretch

WORKDIR /go-control-plane

# Fetch and preserve module dependencies
ENV GOPROXY=https://proxy.golang.org
COPY go.mod ./
RUN go mod download

# circle does not like files in the checkout directory
RUN rm go.mod
RUN rm go.sum

# add envoy
COPY --from=envoyproxy/envoy:v1.15.0 /usr/local/bin/envoy /usr/local/bin/envoy
