// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: envoy/config/filter/udp/udp_proxy/v2alpha/udp_proxy.proto

package v2alpha

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the UDP proxy filter.
type UdpProxyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stat prefix used when emitting UDP proxy filter stats.
	StatPrefix string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// Types that are valid to be assigned to RouteSpecifier:
	//
	//	*UdpProxyConfig_Cluster
	RouteSpecifier isUdpProxyConfig_RouteSpecifier `protobuf_oneof:"route_specifier"`
	// The idle timeout for sessions. Idle is defined as no datagrams between received or sent by
	// the session. The default if not specified is 1 minute.
	IdleTimeout   *durationpb.Duration `protobuf:"bytes,3,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpProxyConfig) Reset() {
	*x = UdpProxyConfig{}
	mi := &file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpProxyConfig) ProtoMessage() {}

func (x *UdpProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpProxyConfig.ProtoReflect.Descriptor instead.
func (*UdpProxyConfig) Descriptor() ([]byte, []int) {
	return file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *UdpProxyConfig) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

func (x *UdpProxyConfig) GetRouteSpecifier() isUdpProxyConfig_RouteSpecifier {
	if x != nil {
		return x.RouteSpecifier
	}
	return nil
}

func (x *UdpProxyConfig) GetCluster() string {
	if x != nil {
		if x, ok := x.RouteSpecifier.(*UdpProxyConfig_Cluster); ok {
			return x.Cluster
		}
	}
	return ""
}

func (x *UdpProxyConfig) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

type isUdpProxyConfig_RouteSpecifier interface {
	isUdpProxyConfig_RouteSpecifier()
}

type UdpProxyConfig_Cluster struct {
	// The upstream cluster to connect to.
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3,oneof"`
}

func (*UdpProxyConfig_Cluster) isUdpProxyConfig_RouteSpecifier() {}

var File_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto protoreflect.FileDescriptor

const file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDesc = "" +
	"\n" +
	"9envoy/config/filter/udp/udp_proxy/v2alpha/udp_proxy.proto\x12)envoy.config.filter.udp.udp_proxy.v2alpha\x1a\x1egoogle/protobuf/duration.proto\x1a\x1eudpa/annotations/migrate.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xb5\x01\n" +
	"\x0eUdpProxyConfig\x12(\n" +
	"\vstat_prefix\x18\x01 \x01(\tB\a\xfaB\x04r\x02 \x01R\n" +
	"statPrefix\x12#\n" +
	"\acluster\x18\x02 \x01(\tB\a\xfaB\x04r\x02 \x01H\x00R\acluster\x12<\n" +
	"\fidle_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vidleTimeoutB\x16\n" +
	"\x0froute_specifier\x12\x03\xf8B\x01B\xd5\x01\xf2\x98\xfe\x8f\x05+\x12)envoy.extensions.filters.udp.udp_proxy.v3\xba\x80\xc8\xd1\x06\x02\x10\x01\n" +
	"7io.envoyproxy.envoy.config.filter.udp.udp_proxy.v2alphaB\rUdpProxyProtoP\x01ZPgithub.com/envoyproxy/go-control-plane/envoy/config/filter/udp/udp_proxy/v2alphab\x06proto3"

var (
	file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescOnce sync.Once
	file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescData []byte
)

func file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescGZIP() []byte {
	file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescOnce.Do(func() {
		file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDesc), len(file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDesc)))
	})
	return file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDescData
}

var file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_goTypes = []any{
	(*UdpProxyConfig)(nil),      // 0: envoy.config.filter.udp.udp_proxy.v2alpha.UdpProxyConfig
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_depIdxs = []int32{
	1, // 0: envoy.config.filter.udp.udp_proxy.v2alpha.UdpProxyConfig.idle_timeout:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_init() }
func file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_init() {
	if File_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto != nil {
		return
	}
	file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_msgTypes[0].OneofWrappers = []any{
		(*UdpProxyConfig_Cluster)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDesc), len(file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_goTypes,
		DependencyIndexes: file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_depIdxs,
		MessageInfos:      file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_msgTypes,
	}.Build()
	File_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto = out.File
	file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_goTypes = nil
	file_envoy_config_filter_udp_udp_proxy_v2alpha_udp_proxy_proto_depIdxs = nil
}
