// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v3alpha/core/base.proto

package envoy_api_v3alpha_core

import (
	fmt "fmt"
	v3alpha "github.com/envoyproxy/go-control-plane/envoy/type/v3alpha"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoutingPriority int32

const (
	RoutingPriority_DEFAULT RoutingPriority = 0
	RoutingPriority_HIGH    RoutingPriority = 1
)

var RoutingPriority_name = map[int32]string{
	0: "DEFAULT",
	1: "HIGH",
}

var RoutingPriority_value = map[string]int32{
	"DEFAULT": 0,
	"HIGH":    1,
}

func (x RoutingPriority) String() string {
	return proto.EnumName(RoutingPriority_name, int32(x))
}

func (RoutingPriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{0}
}

type RequestMethod int32

const (
	RequestMethod_METHOD_UNSPECIFIED RequestMethod = 0
	RequestMethod_GET                RequestMethod = 1
	RequestMethod_HEAD               RequestMethod = 2
	RequestMethod_POST               RequestMethod = 3
	RequestMethod_PUT                RequestMethod = 4
	RequestMethod_DELETE             RequestMethod = 5
	RequestMethod_CONNECT            RequestMethod = 6
	RequestMethod_OPTIONS            RequestMethod = 7
	RequestMethod_TRACE              RequestMethod = 8
	RequestMethod_PATCH              RequestMethod = 9
)

var RequestMethod_name = map[int32]string{
	0: "METHOD_UNSPECIFIED",
	1: "GET",
	2: "HEAD",
	3: "POST",
	4: "PUT",
	5: "DELETE",
	6: "CONNECT",
	7: "OPTIONS",
	8: "TRACE",
	9: "PATCH",
}

var RequestMethod_value = map[string]int32{
	"METHOD_UNSPECIFIED": 0,
	"GET":                1,
	"HEAD":               2,
	"POST":               3,
	"PUT":                4,
	"DELETE":             5,
	"CONNECT":            6,
	"OPTIONS":            7,
	"TRACE":              8,
	"PATCH":              9,
}

func (x RequestMethod) String() string {
	return proto.EnumName(RequestMethod_name, int32(x))
}

func (RequestMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{1}
}

type TrafficDirection int32

const (
	TrafficDirection_UNSPECIFIED TrafficDirection = 0
	TrafficDirection_INBOUND     TrafficDirection = 1
	TrafficDirection_OUTBOUND    TrafficDirection = 2
)

var TrafficDirection_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "INBOUND",
	2: "OUTBOUND",
}

var TrafficDirection_value = map[string]int32{
	"UNSPECIFIED": 0,
	"INBOUND":     1,
	"OUTBOUND":    2,
}

func (x TrafficDirection) String() string {
	return proto.EnumName(TrafficDirection_name, int32(x))
}

func (TrafficDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{2}
}

type SocketOption_SocketState int32

const (
	SocketOption_STATE_PREBIND   SocketOption_SocketState = 0
	SocketOption_STATE_BOUND     SocketOption_SocketState = 1
	SocketOption_STATE_LISTENING SocketOption_SocketState = 2
)

var SocketOption_SocketState_name = map[int32]string{
	0: "STATE_PREBIND",
	1: "STATE_BOUND",
	2: "STATE_LISTENING",
}

var SocketOption_SocketState_value = map[string]int32{
	"STATE_PREBIND":   0,
	"STATE_BOUND":     1,
	"STATE_LISTENING": 2,
}

func (x SocketOption_SocketState) String() string {
	return proto.EnumName(SocketOption_SocketState_name, int32(x))
}

func (SocketOption_SocketState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{12, 0}
}

type Locality struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	SubZone              string   `protobuf:"bytes,3,opt,name=sub_zone,json=subZone,proto3" json:"sub_zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Locality) Reset()         { *m = Locality{} }
func (m *Locality) String() string { return proto.CompactTextString(m) }
func (*Locality) ProtoMessage()    {}
func (*Locality) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{0}
}

func (m *Locality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Locality.Unmarshal(m, b)
}
func (m *Locality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Locality.Marshal(b, m, deterministic)
}
func (m *Locality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locality.Merge(m, src)
}
func (m *Locality) XXX_Size() int {
	return xxx_messageInfo_Locality.Size(m)
}
func (m *Locality) XXX_DiscardUnknown() {
	xxx_messageInfo_Locality.DiscardUnknown(m)
}

var xxx_messageInfo_Locality proto.InternalMessageInfo

func (m *Locality) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Locality) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Locality) GetSubZone() string {
	if m != nil {
		return m.SubZone
	}
	return ""
}

type Node struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cluster              string          `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Metadata             *_struct.Struct `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Locality             *Locality       `protobuf:"bytes,4,opt,name=locality,proto3" json:"locality,omitempty"`
	BuildVersion         string          `protobuf:"bytes,5,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Node) GetMetadata() *_struct.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Node) GetLocality() *Locality {
	if m != nil {
		return m.Locality
	}
	return nil
}

func (m *Node) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

type Metadata struct {
	FilterMetadata       map[string]*_struct.Struct `protobuf:"bytes,1,rep,name=filter_metadata,json=filterMetadata,proto3" json:"filter_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetFilterMetadata() map[string]*_struct.Struct {
	if m != nil {
		return m.FilterMetadata
	}
	return nil
}

type RuntimeUInt32 struct {
	DefaultValue         uint32   `protobuf:"varint,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	RuntimeKey           string   `protobuf:"bytes,3,opt,name=runtime_key,json=runtimeKey,proto3" json:"runtime_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuntimeUInt32) Reset()         { *m = RuntimeUInt32{} }
func (m *RuntimeUInt32) String() string { return proto.CompactTextString(m) }
func (*RuntimeUInt32) ProtoMessage()    {}
func (*RuntimeUInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{3}
}

func (m *RuntimeUInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeUInt32.Unmarshal(m, b)
}
func (m *RuntimeUInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeUInt32.Marshal(b, m, deterministic)
}
func (m *RuntimeUInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeUInt32.Merge(m, src)
}
func (m *RuntimeUInt32) XXX_Size() int {
	return xxx_messageInfo_RuntimeUInt32.Size(m)
}
func (m *RuntimeUInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeUInt32.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeUInt32 proto.InternalMessageInfo

func (m *RuntimeUInt32) GetDefaultValue() uint32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *RuntimeUInt32) GetRuntimeKey() string {
	if m != nil {
		return m.RuntimeKey
	}
	return ""
}

type RuntimeFeatureFlag struct {
	DefaultValue         *wrappers.BoolValue `protobuf:"bytes,1,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	RuntimeKey           string              `protobuf:"bytes,2,opt,name=runtime_key,json=runtimeKey,proto3" json:"runtime_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RuntimeFeatureFlag) Reset()         { *m = RuntimeFeatureFlag{} }
func (m *RuntimeFeatureFlag) String() string { return proto.CompactTextString(m) }
func (*RuntimeFeatureFlag) ProtoMessage()    {}
func (*RuntimeFeatureFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{4}
}

func (m *RuntimeFeatureFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeFeatureFlag.Unmarshal(m, b)
}
func (m *RuntimeFeatureFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeFeatureFlag.Marshal(b, m, deterministic)
}
func (m *RuntimeFeatureFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeFeatureFlag.Merge(m, src)
}
func (m *RuntimeFeatureFlag) XXX_Size() int {
	return xxx_messageInfo_RuntimeFeatureFlag.Size(m)
}
func (m *RuntimeFeatureFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeFeatureFlag.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeFeatureFlag proto.InternalMessageInfo

func (m *RuntimeFeatureFlag) GetDefaultValue() *wrappers.BoolValue {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *RuntimeFeatureFlag) GetRuntimeKey() string {
	if m != nil {
		return m.RuntimeKey
	}
	return ""
}

type HeaderValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderValue) Reset()         { *m = HeaderValue{} }
func (m *HeaderValue) String() string { return proto.CompactTextString(m) }
func (*HeaderValue) ProtoMessage()    {}
func (*HeaderValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{5}
}

func (m *HeaderValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderValue.Unmarshal(m, b)
}
func (m *HeaderValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderValue.Marshal(b, m, deterministic)
}
func (m *HeaderValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderValue.Merge(m, src)
}
func (m *HeaderValue) XXX_Size() int {
	return xxx_messageInfo_HeaderValue.Size(m)
}
func (m *HeaderValue) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderValue.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderValue proto.InternalMessageInfo

func (m *HeaderValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeaderValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HeaderValueOption struct {
	Header               *HeaderValue        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Append               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=append,proto3" json:"append,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HeaderValueOption) Reset()         { *m = HeaderValueOption{} }
func (m *HeaderValueOption) String() string { return proto.CompactTextString(m) }
func (*HeaderValueOption) ProtoMessage()    {}
func (*HeaderValueOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{6}
}

func (m *HeaderValueOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderValueOption.Unmarshal(m, b)
}
func (m *HeaderValueOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderValueOption.Marshal(b, m, deterministic)
}
func (m *HeaderValueOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderValueOption.Merge(m, src)
}
func (m *HeaderValueOption) XXX_Size() int {
	return xxx_messageInfo_HeaderValueOption.Size(m)
}
func (m *HeaderValueOption) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderValueOption.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderValueOption proto.InternalMessageInfo

func (m *HeaderValueOption) GetHeader() *HeaderValue {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HeaderValueOption) GetAppend() *wrappers.BoolValue {
	if m != nil {
		return m.Append
	}
	return nil
}

type HeaderMap struct {
	Headers              []*HeaderValue `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HeaderMap) Reset()         { *m = HeaderMap{} }
func (m *HeaderMap) String() string { return proto.CompactTextString(m) }
func (*HeaderMap) ProtoMessage()    {}
func (*HeaderMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{7}
}

func (m *HeaderMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderMap.Unmarshal(m, b)
}
func (m *HeaderMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderMap.Marshal(b, m, deterministic)
}
func (m *HeaderMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderMap.Merge(m, src)
}
func (m *HeaderMap) XXX_Size() int {
	return xxx_messageInfo_HeaderMap.Size(m)
}
func (m *HeaderMap) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderMap.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderMap proto.InternalMessageInfo

func (m *HeaderMap) GetHeaders() []*HeaderValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

type DataSource struct {
	// Types that are valid to be assigned to Specifier:
	//	*DataSource_Filename
	//	*DataSource_InlineBytes
	//	*DataSource_InlineString
	Specifier            isDataSource_Specifier `protobuf_oneof:"specifier"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DataSource) Reset()         { *m = DataSource{} }
func (m *DataSource) String() string { return proto.CompactTextString(m) }
func (*DataSource) ProtoMessage()    {}
func (*DataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{8}
}

func (m *DataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSource.Unmarshal(m, b)
}
func (m *DataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSource.Marshal(b, m, deterministic)
}
func (m *DataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSource.Merge(m, src)
}
func (m *DataSource) XXX_Size() int {
	return xxx_messageInfo_DataSource.Size(m)
}
func (m *DataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSource.DiscardUnknown(m)
}

var xxx_messageInfo_DataSource proto.InternalMessageInfo

type isDataSource_Specifier interface {
	isDataSource_Specifier()
}

type DataSource_Filename struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type DataSource_InlineBytes struct {
	InlineBytes []byte `protobuf:"bytes,2,opt,name=inline_bytes,json=inlineBytes,proto3,oneof"`
}

type DataSource_InlineString struct {
	InlineString string `protobuf:"bytes,3,opt,name=inline_string,json=inlineString,proto3,oneof"`
}

func (*DataSource_Filename) isDataSource_Specifier() {}

func (*DataSource_InlineBytes) isDataSource_Specifier() {}

func (*DataSource_InlineString) isDataSource_Specifier() {}

func (m *DataSource) GetSpecifier() isDataSource_Specifier {
	if m != nil {
		return m.Specifier
	}
	return nil
}

func (m *DataSource) GetFilename() string {
	if x, ok := m.GetSpecifier().(*DataSource_Filename); ok {
		return x.Filename
	}
	return ""
}

func (m *DataSource) GetInlineBytes() []byte {
	if x, ok := m.GetSpecifier().(*DataSource_InlineBytes); ok {
		return x.InlineBytes
	}
	return nil
}

func (m *DataSource) GetInlineString() string {
	if x, ok := m.GetSpecifier().(*DataSource_InlineString); ok {
		return x.InlineString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DataSource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DataSource_Filename)(nil),
		(*DataSource_InlineBytes)(nil),
		(*DataSource_InlineString)(nil),
	}
}

type RemoteDataSource struct {
	HttpUri              *HttpUri `protobuf:"bytes,1,opt,name=http_uri,json=httpUri,proto3" json:"http_uri,omitempty"`
	Sha256               string   `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteDataSource) Reset()         { *m = RemoteDataSource{} }
func (m *RemoteDataSource) String() string { return proto.CompactTextString(m) }
func (*RemoteDataSource) ProtoMessage()    {}
func (*RemoteDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{9}
}

func (m *RemoteDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDataSource.Unmarshal(m, b)
}
func (m *RemoteDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDataSource.Marshal(b, m, deterministic)
}
func (m *RemoteDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDataSource.Merge(m, src)
}
func (m *RemoteDataSource) XXX_Size() int {
	return xxx_messageInfo_RemoteDataSource.Size(m)
}
func (m *RemoteDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDataSource proto.InternalMessageInfo

func (m *RemoteDataSource) GetHttpUri() *HttpUri {
	if m != nil {
		return m.HttpUri
	}
	return nil
}

func (m *RemoteDataSource) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

type AsyncDataSource struct {
	// Types that are valid to be assigned to Specifier:
	//	*AsyncDataSource_Local
	//	*AsyncDataSource_Remote
	Specifier            isAsyncDataSource_Specifier `protobuf_oneof:"specifier"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AsyncDataSource) Reset()         { *m = AsyncDataSource{} }
func (m *AsyncDataSource) String() string { return proto.CompactTextString(m) }
func (*AsyncDataSource) ProtoMessage()    {}
func (*AsyncDataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{10}
}

func (m *AsyncDataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncDataSource.Unmarshal(m, b)
}
func (m *AsyncDataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncDataSource.Marshal(b, m, deterministic)
}
func (m *AsyncDataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncDataSource.Merge(m, src)
}
func (m *AsyncDataSource) XXX_Size() int {
	return xxx_messageInfo_AsyncDataSource.Size(m)
}
func (m *AsyncDataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncDataSource.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncDataSource proto.InternalMessageInfo

type isAsyncDataSource_Specifier interface {
	isAsyncDataSource_Specifier()
}

type AsyncDataSource_Local struct {
	Local *DataSource `protobuf:"bytes,1,opt,name=local,proto3,oneof"`
}

type AsyncDataSource_Remote struct {
	Remote *RemoteDataSource `protobuf:"bytes,2,opt,name=remote,proto3,oneof"`
}

func (*AsyncDataSource_Local) isAsyncDataSource_Specifier() {}

func (*AsyncDataSource_Remote) isAsyncDataSource_Specifier() {}

func (m *AsyncDataSource) GetSpecifier() isAsyncDataSource_Specifier {
	if m != nil {
		return m.Specifier
	}
	return nil
}

func (m *AsyncDataSource) GetLocal() *DataSource {
	if x, ok := m.GetSpecifier().(*AsyncDataSource_Local); ok {
		return x.Local
	}
	return nil
}

func (m *AsyncDataSource) GetRemote() *RemoteDataSource {
	if x, ok := m.GetSpecifier().(*AsyncDataSource_Remote); ok {
		return x.Remote
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AsyncDataSource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AsyncDataSource_Local)(nil),
		(*AsyncDataSource_Remote)(nil),
	}
}

type TransportSocket struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//	*TransportSocket_TypedConfig
	ConfigType           isTransportSocket_ConfigType `protobuf_oneof:"config_type"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TransportSocket) Reset()         { *m = TransportSocket{} }
func (m *TransportSocket) String() string { return proto.CompactTextString(m) }
func (*TransportSocket) ProtoMessage()    {}
func (*TransportSocket) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{11}
}

func (m *TransportSocket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportSocket.Unmarshal(m, b)
}
func (m *TransportSocket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportSocket.Marshal(b, m, deterministic)
}
func (m *TransportSocket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportSocket.Merge(m, src)
}
func (m *TransportSocket) XXX_Size() int {
	return xxx_messageInfo_TransportSocket.Size(m)
}
func (m *TransportSocket) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportSocket.DiscardUnknown(m)
}

var xxx_messageInfo_TransportSocket proto.InternalMessageInfo

func (m *TransportSocket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isTransportSocket_ConfigType interface {
	isTransportSocket_ConfigType()
}

type TransportSocket_TypedConfig struct {
	TypedConfig *any.Any `protobuf:"bytes,3,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*TransportSocket_TypedConfig) isTransportSocket_ConfigType() {}

func (m *TransportSocket) GetConfigType() isTransportSocket_ConfigType {
	if m != nil {
		return m.ConfigType
	}
	return nil
}

func (m *TransportSocket) GetTypedConfig() *any.Any {
	if x, ok := m.GetConfigType().(*TransportSocket_TypedConfig); ok {
		return x.TypedConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransportSocket) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransportSocket_TypedConfig)(nil),
	}
}

type SocketOption struct {
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Level       int64  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Name        int64  `protobuf:"varint,3,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*SocketOption_IntValue
	//	*SocketOption_BufValue
	Value                isSocketOption_Value     `protobuf_oneof:"value"`
	State                SocketOption_SocketState `protobuf:"varint,6,opt,name=state,proto3,enum=envoy.api.v3alpha.core.SocketOption_SocketState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SocketOption) Reset()         { *m = SocketOption{} }
func (m *SocketOption) String() string { return proto.CompactTextString(m) }
func (*SocketOption) ProtoMessage()    {}
func (*SocketOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{12}
}

func (m *SocketOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketOption.Unmarshal(m, b)
}
func (m *SocketOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketOption.Marshal(b, m, deterministic)
}
func (m *SocketOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketOption.Merge(m, src)
}
func (m *SocketOption) XXX_Size() int {
	return xxx_messageInfo_SocketOption.Size(m)
}
func (m *SocketOption) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketOption.DiscardUnknown(m)
}

var xxx_messageInfo_SocketOption proto.InternalMessageInfo

func (m *SocketOption) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SocketOption) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *SocketOption) GetName() int64 {
	if m != nil {
		return m.Name
	}
	return 0
}

type isSocketOption_Value interface {
	isSocketOption_Value()
}

type SocketOption_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type SocketOption_BufValue struct {
	BufValue []byte `protobuf:"bytes,5,opt,name=buf_value,json=bufValue,proto3,oneof"`
}

func (*SocketOption_IntValue) isSocketOption_Value() {}

func (*SocketOption_BufValue) isSocketOption_Value() {}

func (m *SocketOption) GetValue() isSocketOption_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SocketOption) GetIntValue() int64 {
	if x, ok := m.GetValue().(*SocketOption_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *SocketOption) GetBufValue() []byte {
	if x, ok := m.GetValue().(*SocketOption_BufValue); ok {
		return x.BufValue
	}
	return nil
}

func (m *SocketOption) GetState() SocketOption_SocketState {
	if m != nil {
		return m.State
	}
	return SocketOption_STATE_PREBIND
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SocketOption) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SocketOption_IntValue)(nil),
		(*SocketOption_BufValue)(nil),
	}
}

type RuntimeFractionalPercent struct {
	DefaultValue         *v3alpha.FractionalPercent `protobuf:"bytes,1,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	RuntimeKey           string                     `protobuf:"bytes,2,opt,name=runtime_key,json=runtimeKey,proto3" json:"runtime_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RuntimeFractionalPercent) Reset()         { *m = RuntimeFractionalPercent{} }
func (m *RuntimeFractionalPercent) String() string { return proto.CompactTextString(m) }
func (*RuntimeFractionalPercent) ProtoMessage()    {}
func (*RuntimeFractionalPercent) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{13}
}

func (m *RuntimeFractionalPercent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeFractionalPercent.Unmarshal(m, b)
}
func (m *RuntimeFractionalPercent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeFractionalPercent.Marshal(b, m, deterministic)
}
func (m *RuntimeFractionalPercent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeFractionalPercent.Merge(m, src)
}
func (m *RuntimeFractionalPercent) XXX_Size() int {
	return xxx_messageInfo_RuntimeFractionalPercent.Size(m)
}
func (m *RuntimeFractionalPercent) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeFractionalPercent.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeFractionalPercent proto.InternalMessageInfo

func (m *RuntimeFractionalPercent) GetDefaultValue() *v3alpha.FractionalPercent {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *RuntimeFractionalPercent) GetRuntimeKey() string {
	if m != nil {
		return m.RuntimeKey
	}
	return ""
}

type ControlPlane struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlPlane) Reset()         { *m = ControlPlane{} }
func (m *ControlPlane) String() string { return proto.CompactTextString(m) }
func (*ControlPlane) ProtoMessage()    {}
func (*ControlPlane) Descriptor() ([]byte, []int) {
	return fileDescriptor_30091e7eb5eb989f, []int{14}
}

func (m *ControlPlane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlane.Unmarshal(m, b)
}
func (m *ControlPlane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlane.Marshal(b, m, deterministic)
}
func (m *ControlPlane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlane.Merge(m, src)
}
func (m *ControlPlane) XXX_Size() int {
	return xxx_messageInfo_ControlPlane.Size(m)
}
func (m *ControlPlane) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlane.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlane proto.InternalMessageInfo

func (m *ControlPlane) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func init() {
	proto.RegisterEnum("envoy.api.v3alpha.core.RoutingPriority", RoutingPriority_name, RoutingPriority_value)
	proto.RegisterEnum("envoy.api.v3alpha.core.RequestMethod", RequestMethod_name, RequestMethod_value)
	proto.RegisterEnum("envoy.api.v3alpha.core.TrafficDirection", TrafficDirection_name, TrafficDirection_value)
	proto.RegisterEnum("envoy.api.v3alpha.core.SocketOption_SocketState", SocketOption_SocketState_name, SocketOption_SocketState_value)
	proto.RegisterType((*Locality)(nil), "envoy.api.v3alpha.core.Locality")
	proto.RegisterType((*Node)(nil), "envoy.api.v3alpha.core.Node")
	proto.RegisterType((*Metadata)(nil), "envoy.api.v3alpha.core.Metadata")
	proto.RegisterMapType((map[string]*_struct.Struct)(nil), "envoy.api.v3alpha.core.Metadata.FilterMetadataEntry")
	proto.RegisterType((*RuntimeUInt32)(nil), "envoy.api.v3alpha.core.RuntimeUInt32")
	proto.RegisterType((*RuntimeFeatureFlag)(nil), "envoy.api.v3alpha.core.RuntimeFeatureFlag")
	proto.RegisterType((*HeaderValue)(nil), "envoy.api.v3alpha.core.HeaderValue")
	proto.RegisterType((*HeaderValueOption)(nil), "envoy.api.v3alpha.core.HeaderValueOption")
	proto.RegisterType((*HeaderMap)(nil), "envoy.api.v3alpha.core.HeaderMap")
	proto.RegisterType((*DataSource)(nil), "envoy.api.v3alpha.core.DataSource")
	proto.RegisterType((*RemoteDataSource)(nil), "envoy.api.v3alpha.core.RemoteDataSource")
	proto.RegisterType((*AsyncDataSource)(nil), "envoy.api.v3alpha.core.AsyncDataSource")
	proto.RegisterType((*TransportSocket)(nil), "envoy.api.v3alpha.core.TransportSocket")
	proto.RegisterType((*SocketOption)(nil), "envoy.api.v3alpha.core.SocketOption")
	proto.RegisterType((*RuntimeFractionalPercent)(nil), "envoy.api.v3alpha.core.RuntimeFractionalPercent")
	proto.RegisterType((*ControlPlane)(nil), "envoy.api.v3alpha.core.ControlPlane")
}

func init() { proto.RegisterFile("envoy/api/v3alpha/core/base.proto", fileDescriptor_30091e7eb5eb989f) }

var fileDescriptor_30091e7eb5eb989f = []byte{
	// 1270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xfa, 0xdf, 0xc7, 0x4e, 0xb3, 0x9d, 0x56, 0x6d, 0x1a, 0x68, 0x63, 0x5c, 0x2a, 0x45,
	0x15, 0xd8, 0x28, 0x01, 0x04, 0x15, 0x20, 0x79, 0xed, 0x4d, 0xed, 0x92, 0xd8, 0x66, 0xbd, 0xee,
	0x45, 0x25, 0xb0, 0xc6, 0xde, 0xb1, 0x33, 0xea, 0x66, 0x77, 0x99, 0x9d, 0x0d, 0xb8, 0x57, 0x15,
	0x17, 0x48, 0xe5, 0x02, 0x89, 0x67, 0xe0, 0x45, 0xb8, 0x41, 0xe2, 0x91, 0x50, 0xae, 0xd0, 0xfc,
	0x6c, 0xea, 0xa6, 0x71, 0xc5, 0xdd, 0x9e, 0xef, 0x9c, 0xef, 0xfc, 0xcf, 0xb1, 0xe1, 0x03, 0x12,
	0x9c, 0x85, 0xcb, 0x26, 0x8e, 0x68, 0xf3, 0xec, 0x00, 0xfb, 0xd1, 0x09, 0x6e, 0xce, 0x42, 0x46,
	0x9a, 0x53, 0x1c, 0x93, 0x46, 0xc4, 0x42, 0x1e, 0xa2, 0x5b, 0xd2, 0xa4, 0x81, 0x23, 0xda, 0xd0,
	0x26, 0x0d, 0x61, 0xb2, 0xf3, 0x60, 0x0d, 0xf5, 0x84, 0xf3, 0x68, 0x92, 0x30, 0xaa, 0xe8, 0x3b,
	0x35, 0x65, 0xc6, 0x97, 0x11, 0xb9, 0xb0, 0x8b, 0x08, 0x9b, 0x91, 0x80, 0x6b, 0x8b, 0x3b, 0x8b,
	0x30, 0x5c, 0xf8, 0xa4, 0x29, 0xa5, 0x69, 0x32, 0x6f, 0xe2, 0x60, 0xa9, 0x55, 0xef, 0x5f, 0x56,
	0xc5, 0x9c, 0x25, 0xb3, 0x94, 0x78, 0xef, 0xb2, 0xf6, 0x27, 0x86, 0xa3, 0x88, 0xb0, 0x58, 0xeb,
	0x6f, 0x9f, 0x61, 0x9f, 0x7a, 0x98, 0x93, 0x66, 0xfa, 0xa1, 0x14, 0xf5, 0xef, 0xa0, 0x74, 0x14,
	0xce, 0xb0, 0x4f, 0xf9, 0x12, 0xdd, 0x82, 0x02, 0x23, 0x0b, 0x1a, 0x06, 0xdb, 0x46, 0xcd, 0xd8,
	0x2b, 0x3b, 0x5a, 0x42, 0x08, 0x72, 0x2f, 0xc2, 0x80, 0x6c, 0x67, 0x24, 0x2a, 0xbf, 0xd1, 0x1d,
	0x28, 0xc5, 0xc9, 0x74, 0x22, 0xf1, 0xac, 0xc4, 0x8b, 0x71, 0x32, 0x7d, 0x16, 0x06, 0xa4, 0xfe,
	0x8f, 0x01, 0xb9, 0x7e, 0xe8, 0x11, 0x74, 0x0d, 0x32, 0xd4, 0xd3, 0xbe, 0x32, 0xd4, 0x43, 0xdb,
	0x50, 0x9c, 0xf9, 0x49, 0xcc, 0x09, 0xd3, 0xae, 0x52, 0x11, 0x1d, 0x40, 0xe9, 0x94, 0x70, 0xec,
	0x61, 0x8e, 0xa5, 0xb7, 0xca, 0xfe, 0xed, 0x86, 0xaa, 0xa8, 0x91, 0x56, 0xd4, 0x18, 0xc9, 0x7a,
	0x9d, 0x0b, 0x43, 0xf4, 0x15, 0x94, 0x7c, 0x9d, 0xfa, 0x76, 0x4e, 0x92, 0x6a, 0x8d, 0xab, 0x07,
	0xd4, 0x48, 0x4b, 0x74, 0x2e, 0x18, 0xe8, 0x3e, 0x6c, 0x4e, 0x13, 0xea, 0x7b, 0x93, 0x33, 0xc2,
	0x62, 0x51, 0x73, 0x5e, 0xa6, 0x54, 0x95, 0xe0, 0x53, 0x85, 0xd5, 0xff, 0x36, 0xa0, 0x74, 0x9c,
	0xc6, 0xfb, 0x1e, 0xb6, 0xe6, 0xd4, 0xe7, 0x84, 0x4d, 0x2e, 0x72, 0x35, 0x6a, 0xd9, 0xbd, 0xca,
	0xfe, 0xa7, 0xeb, 0xc2, 0xa6, 0xd4, 0xc6, 0xa1, 0xe4, 0xa5, 0xa2, 0x1d, 0x70, 0xb6, 0x74, 0xae,
	0xcd, 0xdf, 0x00, 0x77, 0x9e, 0xc1, 0x8d, 0x2b, 0xcc, 0x90, 0x09, 0xd9, 0xe7, 0x64, 0xa9, 0xbb,
	0x28, 0x3e, 0xd1, 0xc7, 0x90, 0x3f, 0xc3, 0x7e, 0xa2, 0xe6, 0xf1, 0x8e, 0x4e, 0x29, 0xab, 0x47,
	0x99, 0x2f, 0x8c, 0xfa, 0x0f, 0xb0, 0xe9, 0x24, 0x01, 0xa7, 0xa7, 0x64, 0xdc, 0x0b, 0xf8, 0xc1,
	0xbe, 0xa8, 0xde, 0x23, 0x73, 0x9c, 0xf8, 0x7c, 0xf2, 0xda, 0xd7, 0xa6, 0x53, 0xd5, 0xe0, 0x53,
	0x81, 0xa1, 0x3d, 0xa8, 0x30, 0xc5, 0x9a, 0x88, 0x14, 0xe4, 0x98, 0xad, 0xe2, 0xb9, 0x95, 0x63,
	0x99, 0x9a, 0xe1, 0x80, 0xd6, 0x7d, 0x4b, 0x96, 0xf5, 0x57, 0x06, 0x20, 0x1d, 0xe0, 0x90, 0x60,
	0x9e, 0x30, 0x72, 0xe8, 0xe3, 0x05, 0xea, 0x5d, 0x8e, 0x62, 0xc8, 0x8c, 0x77, 0xde, 0xca, 0xd8,
	0x0a, 0x43, 0x5f, 0xc6, 0xb4, 0x4a, 0xe7, 0x56, 0xfe, 0x37, 0x23, 0x63, 0x1a, 0xef, 0xce, 0x25,
	0xb3, 0x3e, 0x97, 0x63, 0xa8, 0x74, 0x09, 0xf6, 0x08, 0x53, 0xc4, 0xbb, 0x2b, 0xfd, 0xb3, 0x2a,
	0xe7, 0x56, 0x89, 0x15, 0x6a, 0xc6, 0xde, 0xcb, 0x97, 0x86, 0x6a, 0xe6, 0xee, 0x6a, 0x33, 0xcb,
	0x56, 0xf9, 0xdc, 0x2a, 0xb0, 0x9c, 0x54, 0x2b, 0xbc, 0xfe, 0xbb, 0x01, 0xd7, 0x57, 0xfc, 0x0d,
	0x22, 0x2e, 0x9e, 0x84, 0x0d, 0x85, 0x13, 0x09, 0xea, 0x92, 0xee, 0xaf, 0x5b, 0x81, 0x15, 0xea,
	0x4a, 0x6d, 0x9a, 0x8c, 0xf6, 0xa1, 0x20, 0x9e, 0x69, 0xe0, 0xe9, 0x59, 0xbe, 0xa3, 0x33, 0x8e,
	0xb6, 0xac, 0x3f, 0x81, 0xb2, 0x72, 0x7a, 0x8c, 0x23, 0xf4, 0x35, 0x14, 0x95, 0xab, 0x58, 0xef,
	0xe2, 0xff, 0x49, 0xc4, 0x49, 0x39, 0xf5, 0x3f, 0x0d, 0x80, 0x0e, 0xe6, 0x78, 0x14, 0x26, 0x6c,
	0x46, 0xd0, 0x03, 0x28, 0xcd, 0xa9, 0x4f, 0x02, 0x7c, 0x4a, 0x74, 0xc3, 0xd2, 0x0e, 0x77, 0x37,
	0x9c, 0x0b, 0x15, 0xfa, 0x08, 0xaa, 0x34, 0xf0, 0x69, 0x40, 0x26, 0xd3, 0x25, 0x27, 0xb1, 0xcc,
	0xbd, 0x2a, 0x4d, 0x5f, 0x64, 0x4c, 0x61, 0x5a, 0x51, 0x6a, 0x4b, 0x68, 0x51, 0x03, 0x36, 0xb5,
	0x75, 0xcc, 0x19, 0x0d, 0x16, 0x97, 0xf6, 0xa8, 0xbb, 0xe1, 0x68, 0x6f, 0x23, 0xa9, 0xb6, 0x4c,
	0x28, 0xc7, 0x11, 0x99, 0xd1, 0x39, 0x25, 0x0c, 0x65, 0xff, 0xb5, 0x8c, 0xfa, 0x12, 0x4c, 0x87,
	0x9c, 0x86, 0x9c, 0xac, 0xa4, 0xda, 0x81, 0x52, 0x7a, 0x5d, 0xf5, 0x08, 0x76, 0xd7, 0x56, 0xce,
	0x79, 0x34, 0x66, 0x74, 0xa5, 0xfd, 0xc5, 0x13, 0x05, 0xa1, 0x5d, 0x28, 0xc4, 0x27, 0x78, 0xff,
	0xb3, 0xcf, 0x2f, 0x2f, 0x94, 0x86, 0x45, 0x83, 0xb6, 0x5a, 0xf1, 0x32, 0x98, 0xad, 0x84, 0x7e,
	0x04, 0x79, 0x79, 0x45, 0x74, 0xdc, 0xfa, 0xba, 0xb8, 0xaf, 0x29, 0xdd, 0x0d, 0x47, 0x51, 0x90,
	0x25, 0x4e, 0xac, 0x28, 0x45, 0x0f, 0x7c, 0x6f, 0x1d, 0xf9, 0x72, 0xc1, 0xdd, 0x0d, 0x47, 0x33,
	0xaf, 0x68, 0xd0, 0xaf, 0x06, 0x6c, 0xb9, 0x0c, 0x07, 0x71, 0x14, 0x32, 0x3e, 0x0a, 0x67, 0xcf,
	0x09, 0x47, 0xef, 0x41, 0xee, 0x8a, 0x39, 0x3a, 0x12, 0x44, 0x5f, 0x42, 0x55, 0xfc, 0x0a, 0x79,
	0x93, 0x59, 0x18, 0xcc, 0xe9, 0x42, 0xdf, 0xdc, 0x9b, 0x6f, 0x6d, 0x5f, 0x2b, 0x58, 0x8a, 0x71,
	0x4a, 0xdb, 0xb6, 0x34, 0xb5, 0x36, 0xa1, 0xa2, 0x48, 0x13, 0x81, 0x3e, 0xc9, 0x95, 0x32, 0x66,
	0xd6, 0x29, 0x28, 0xa8, 0xfe, 0x57, 0x06, 0xaa, 0x2a, 0xbe, 0x7e, 0x27, 0x35, 0xa8, 0x78, 0x24,
	0x9e, 0x31, 0x2a, 0x45, 0x7d, 0xc5, 0x56, 0x21, 0x74, 0x13, 0xf2, 0x3e, 0x39, 0x23, 0xbe, 0x6c,
	0x48, 0xd6, 0x51, 0x82, 0xf8, 0xc9, 0x91, 0xd9, 0x67, 0x25, 0xa8, 0x92, 0xbe, 0x0b, 0x65, 0x1a,
	0xa4, 0x97, 0x44, 0x1c, 0xfc, 0xac, 0xd8, 0x4a, 0x1a, 0xf0, 0xf4, 0xa1, 0x97, 0xa7, 0xc9, 0x5c,
	0xab, 0xc5, 0x31, 0xaf, 0x0a, 0xf5, 0x34, 0x99, 0x2b, 0xf5, 0x10, 0xf2, 0x31, 0xc7, 0x9c, 0x6c,
	0x8b, 0xe7, 0x7f, 0x6d, 0xff, 0x93, 0x75, 0x8d, 0x5f, 0x4d, 0x5f, 0x0b, 0x23, 0xc1, 0x93, 0xeb,
	0xf3, 0x8b, 0x5c, 0x1f, 0xe5, 0xa8, 0x7e, 0x08, 0x95, 0x15, 0x3d, 0xba, 0x0e, 0x9b, 0x23, 0xb7,
	0xe5, 0xda, 0x93, 0xa1, 0x63, 0x5b, 0xbd, 0x7e, 0xc7, 0xdc, 0x40, 0x5b, 0x50, 0x51, 0x90, 0x35,
	0x18, 0xf7, 0x3b, 0xa6, 0x81, 0x6e, 0xc0, 0x96, 0x02, 0x8e, 0x7a, 0x23, 0xd7, 0xee, 0xf7, 0xfa,
	0x8f, 0xcd, 0x8c, 0x55, 0xd5, 0x27, 0x48, 0xcd, 0xf2, 0x0f, 0x03, 0xb6, 0xd3, 0x53, 0xca, 0xf0,
	0x4c, 0xa4, 0x81, 0xfd, 0xa1, 0xfa, 0x97, 0x80, 0xdc, 0xab, 0x0f, 0xea, 0x03, 0x5d, 0x8c, 0x98,
	0xc8, 0x45, 0x35, 0x6f, 0xb1, 0xd7, 0xde, 0xd6, 0xdd, 0x2b, 0x6e, 0xeb, 0x1b, 0x27, 0xb5, 0x01,
	0xd5, 0x76, 0x18, 0x70, 0x16, 0xfa, 0x43, 0x1f, 0x07, 0x04, 0xdd, 0x03, 0xa0, 0x1e, 0x09, 0xb8,
	0x5c, 0x41, 0x3d, 0xd4, 0x15, 0xe4, 0xe1, 0x1e, 0x6c, 0x39, 0x61, 0xc2, 0x69, 0xb0, 0x18, 0x32,
	0x1a, 0x32, 0xf1, 0x73, 0x5b, 0x81, 0x62, 0xc7, 0x3e, 0x6c, 0x8d, 0x8f, 0x5c, 0x73, 0x03, 0x95,
	0x20, 0xd7, 0xed, 0x3d, 0xee, 0x9a, 0xc6, 0xc3, 0x57, 0x06, 0x6c, 0x3a, 0xe4, 0xc7, 0x84, 0xc4,
	0xfc, 0x98, 0xf0, 0x93, 0xd0, 0x43, 0xb7, 0x00, 0x1d, 0xdb, 0x6e, 0x77, 0xd0, 0x99, 0x8c, 0xfb,
	0xa3, 0xa1, 0xdd, 0xee, 0x1d, 0xf6, 0x6c, 0xd1, 0xcb, 0x22, 0x64, 0x1f, 0xdb, 0xae, 0x69, 0x48,
	0xb2, 0xdd, 0xea, 0x98, 0x19, 0xf1, 0x35, 0x1c, 0x8c, 0x5c, 0x33, 0x2b, 0x94, 0xc3, 0xb1, 0x6b,
	0xe6, 0x10, 0x40, 0xa1, 0x63, 0x1f, 0xd9, 0xae, 0x6d, 0xe6, 0x45, 0xc8, 0xf6, 0xa0, 0xdf, 0xb7,
	0xdb, 0xae, 0x59, 0x10, 0xc2, 0x60, 0xe8, 0xf6, 0x06, 0xfd, 0x91, 0x59, 0x44, 0x65, 0xc8, 0xbb,
	0x4e, 0xab, 0x6d, 0x9b, 0x25, 0xf1, 0x39, 0x6c, 0xb9, 0xed, 0xae, 0x59, 0x7e, 0xf8, 0x0d, 0x98,
	0x2e, 0xc3, 0xf3, 0x39, 0x9d, 0x75, 0x28, 0x23, 0xb2, 0x77, 0x62, 0x82, 0x6f, 0xa6, 0x51, 0x81,
	0x62, 0xaf, 0x9f, 0x8e, 0xb3, 0x0a, 0xa5, 0xc1, 0xd8, 0x55, 0x52, 0xc6, 0x3a, 0x80, 0x0f, 0x69,
	0xa8, 0x26, 0x11, 0xb1, 0xf0, 0xe7, 0xe5, 0x9a, 0x0d, 0xb3, 0xca, 0x16, 0x8e, 0xc9, 0x50, 0x3c,
	0xb1, 0xa1, 0x31, 0x2d, 0xc8, 0xb7, 0x76, 0xf0, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xa9,
	0x3f, 0xaf, 0x7e, 0x0a, 0x00, 0x00,
}
