// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v2/listener.proto

package envoy_api_v2

import (
	fmt "fmt"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core"
	listener "github.com/envoyproxy/go-control-plane/envoy/api/v2/listener"
	v2 "github.com/envoyproxy/go-control-plane/envoy/config/listener/v2"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Listener_DrainType int32

const (
	Listener_DEFAULT     Listener_DrainType = 0
	Listener_MODIFY_ONLY Listener_DrainType = 1
)

var Listener_DrainType_name = map[int32]string{
	0: "DEFAULT",
	1: "MODIFY_ONLY",
}

var Listener_DrainType_value = map[string]int32{
	"DEFAULT":     0,
	"MODIFY_ONLY": 1,
}

func (x Listener_DrainType) String() string {
	return proto.EnumName(Listener_DrainType_name, int32(x))
}

func (Listener_DrainType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f8f4b6e66505502, []int{0, 0}
}

type Listener struct {
	Name                             string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address                          *core.Address                     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FilterChains                     []*listener.FilterChain           `protobuf:"bytes,3,rep,name=filter_chains,json=filterChains,proto3" json:"filter_chains,omitempty"`
	UseOriginalDst                   *wrappers.BoolValue               `protobuf:"bytes,4,opt,name=use_original_dst,json=useOriginalDst,proto3" json:"use_original_dst,omitempty"` // Deprecated: Do not use.
	PerConnectionBufferLimitBytes    *wrappers.UInt32Value             `protobuf:"bytes,5,opt,name=per_connection_buffer_limit_bytes,json=perConnectionBufferLimitBytes,proto3" json:"per_connection_buffer_limit_bytes,omitempty"`
	Metadata                         *core.Metadata                    `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DeprecatedV1                     *Listener_DeprecatedV1            `protobuf:"bytes,7,opt,name=deprecated_v1,json=deprecatedV1,proto3" json:"deprecated_v1,omitempty"`
	DrainType                        Listener_DrainType                `protobuf:"varint,8,opt,name=drain_type,json=drainType,proto3,enum=envoy.api.v2.Listener_DrainType" json:"drain_type,omitempty"`
	ListenerFilters                  []*listener.ListenerFilter        `protobuf:"bytes,9,rep,name=listener_filters,json=listenerFilters,proto3" json:"listener_filters,omitempty"`
	ListenerFiltersTimeout           *duration.Duration                `protobuf:"bytes,15,opt,name=listener_filters_timeout,json=listenerFiltersTimeout,proto3" json:"listener_filters_timeout,omitempty"`
	ContinueOnListenerFiltersTimeout bool                              `protobuf:"varint,17,opt,name=continue_on_listener_filters_timeout,json=continueOnListenerFiltersTimeout,proto3" json:"continue_on_listener_filters_timeout,omitempty"`
	Transparent                      *wrappers.BoolValue               `protobuf:"bytes,10,opt,name=transparent,proto3" json:"transparent,omitempty"`
	Freebind                         *wrappers.BoolValue               `protobuf:"bytes,11,opt,name=freebind,proto3" json:"freebind,omitempty"`
	SocketOptions                    []*core.SocketOption              `protobuf:"bytes,13,rep,name=socket_options,json=socketOptions,proto3" json:"socket_options,omitempty"`
	TcpFastOpenQueueLength           *wrappers.UInt32Value             `protobuf:"bytes,12,opt,name=tcp_fast_open_queue_length,json=tcpFastOpenQueueLength,proto3" json:"tcp_fast_open_queue_length,omitempty"`
	TrafficDirection                 core.TrafficDirection             `protobuf:"varint,16,opt,name=traffic_direction,json=trafficDirection,proto3,enum=envoy.api.v2.core.TrafficDirection" json:"traffic_direction,omitempty"`
	UdpListenerConfig                *listener.UdpListenerConfig       `protobuf:"bytes,18,opt,name=udp_listener_config,json=udpListenerConfig,proto3" json:"udp_listener_config,omitempty"`
	ApiListener                      *v2.ApiListener                   `protobuf:"bytes,19,opt,name=api_listener,json=apiListener,proto3" json:"api_listener,omitempty"`
	ConnectionBalanceConfig          *Listener_ConnectionBalanceConfig `protobuf:"bytes,20,opt,name=connection_balance_config,json=connectionBalanceConfig,proto3" json:"connection_balance_config,omitempty"`
	ReusePort                        bool                              `protobuf:"varint,21,opt,name=reuse_port,json=reusePort,proto3" json:"reuse_port,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                          `json:"-"`
	XXX_unrecognized                 []byte                            `json:"-"`
	XXX_sizecache                    int32                             `json:"-"`
}

func (m *Listener) Reset()         { *m = Listener{} }
func (m *Listener) String() string { return proto.CompactTextString(m) }
func (*Listener) ProtoMessage()    {}
func (*Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f8f4b6e66505502, []int{0}
}

func (m *Listener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener.Unmarshal(m, b)
}
func (m *Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener.Marshal(b, m, deterministic)
}
func (m *Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener.Merge(m, src)
}
func (m *Listener) XXX_Size() int {
	return xxx_messageInfo_Listener.Size(m)
}
func (m *Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_Listener proto.InternalMessageInfo

func (m *Listener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listener) GetAddress() *core.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Listener) GetFilterChains() []*listener.FilterChain {
	if m != nil {
		return m.FilterChains
	}
	return nil
}

// Deprecated: Do not use.
func (m *Listener) GetUseOriginalDst() *wrappers.BoolValue {
	if m != nil {
		return m.UseOriginalDst
	}
	return nil
}

func (m *Listener) GetPerConnectionBufferLimitBytes() *wrappers.UInt32Value {
	if m != nil {
		return m.PerConnectionBufferLimitBytes
	}
	return nil
}

func (m *Listener) GetMetadata() *core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Listener) GetDeprecatedV1() *Listener_DeprecatedV1 {
	if m != nil {
		return m.DeprecatedV1
	}
	return nil
}

func (m *Listener) GetDrainType() Listener_DrainType {
	if m != nil {
		return m.DrainType
	}
	return Listener_DEFAULT
}

func (m *Listener) GetListenerFilters() []*listener.ListenerFilter {
	if m != nil {
		return m.ListenerFilters
	}
	return nil
}

func (m *Listener) GetListenerFiltersTimeout() *duration.Duration {
	if m != nil {
		return m.ListenerFiltersTimeout
	}
	return nil
}

func (m *Listener) GetContinueOnListenerFiltersTimeout() bool {
	if m != nil {
		return m.ContinueOnListenerFiltersTimeout
	}
	return false
}

func (m *Listener) GetTransparent() *wrappers.BoolValue {
	if m != nil {
		return m.Transparent
	}
	return nil
}

func (m *Listener) GetFreebind() *wrappers.BoolValue {
	if m != nil {
		return m.Freebind
	}
	return nil
}

func (m *Listener) GetSocketOptions() []*core.SocketOption {
	if m != nil {
		return m.SocketOptions
	}
	return nil
}

func (m *Listener) GetTcpFastOpenQueueLength() *wrappers.UInt32Value {
	if m != nil {
		return m.TcpFastOpenQueueLength
	}
	return nil
}

func (m *Listener) GetTrafficDirection() core.TrafficDirection {
	if m != nil {
		return m.TrafficDirection
	}
	return core.TrafficDirection_UNSPECIFIED
}

func (m *Listener) GetUdpListenerConfig() *listener.UdpListenerConfig {
	if m != nil {
		return m.UdpListenerConfig
	}
	return nil
}

func (m *Listener) GetApiListener() *v2.ApiListener {
	if m != nil {
		return m.ApiListener
	}
	return nil
}

func (m *Listener) GetConnectionBalanceConfig() *Listener_ConnectionBalanceConfig {
	if m != nil {
		return m.ConnectionBalanceConfig
	}
	return nil
}

func (m *Listener) GetReusePort() bool {
	if m != nil {
		return m.ReusePort
	}
	return false
}

type Listener_DeprecatedV1 struct {
	BindToPort           *wrappers.BoolValue `protobuf:"bytes,1,opt,name=bind_to_port,json=bindToPort,proto3" json:"bind_to_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Listener_DeprecatedV1) Reset()         { *m = Listener_DeprecatedV1{} }
func (m *Listener_DeprecatedV1) String() string { return proto.CompactTextString(m) }
func (*Listener_DeprecatedV1) ProtoMessage()    {}
func (*Listener_DeprecatedV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f8f4b6e66505502, []int{0, 0}
}

func (m *Listener_DeprecatedV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener_DeprecatedV1.Unmarshal(m, b)
}
func (m *Listener_DeprecatedV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener_DeprecatedV1.Marshal(b, m, deterministic)
}
func (m *Listener_DeprecatedV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener_DeprecatedV1.Merge(m, src)
}
func (m *Listener_DeprecatedV1) XXX_Size() int {
	return xxx_messageInfo_Listener_DeprecatedV1.Size(m)
}
func (m *Listener_DeprecatedV1) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener_DeprecatedV1.DiscardUnknown(m)
}

var xxx_messageInfo_Listener_DeprecatedV1 proto.InternalMessageInfo

func (m *Listener_DeprecatedV1) GetBindToPort() *wrappers.BoolValue {
	if m != nil {
		return m.BindToPort
	}
	return nil
}

type Listener_ConnectionBalanceConfig struct {
	// Types that are valid to be assigned to BalanceType:
	//	*Listener_ConnectionBalanceConfig_ExactBalance_
	BalanceType          isListener_ConnectionBalanceConfig_BalanceType `protobuf_oneof:"balance_type"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Listener_ConnectionBalanceConfig) Reset()         { *m = Listener_ConnectionBalanceConfig{} }
func (m *Listener_ConnectionBalanceConfig) String() string { return proto.CompactTextString(m) }
func (*Listener_ConnectionBalanceConfig) ProtoMessage()    {}
func (*Listener_ConnectionBalanceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f8f4b6e66505502, []int{0, 1}
}

func (m *Listener_ConnectionBalanceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig.Unmarshal(m, b)
}
func (m *Listener_ConnectionBalanceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig.Marshal(b, m, deterministic)
}
func (m *Listener_ConnectionBalanceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener_ConnectionBalanceConfig.Merge(m, src)
}
func (m *Listener_ConnectionBalanceConfig) XXX_Size() int {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig.Size(m)
}
func (m *Listener_ConnectionBalanceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener_ConnectionBalanceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Listener_ConnectionBalanceConfig proto.InternalMessageInfo

type isListener_ConnectionBalanceConfig_BalanceType interface {
	isListener_ConnectionBalanceConfig_BalanceType()
}

type Listener_ConnectionBalanceConfig_ExactBalance_ struct {
	ExactBalance *Listener_ConnectionBalanceConfig_ExactBalance `protobuf:"bytes,1,opt,name=exact_balance,json=exactBalance,proto3,oneof"`
}

func (*Listener_ConnectionBalanceConfig_ExactBalance_) isListener_ConnectionBalanceConfig_BalanceType() {
}

func (m *Listener_ConnectionBalanceConfig) GetBalanceType() isListener_ConnectionBalanceConfig_BalanceType {
	if m != nil {
		return m.BalanceType
	}
	return nil
}

func (m *Listener_ConnectionBalanceConfig) GetExactBalance() *Listener_ConnectionBalanceConfig_ExactBalance {
	if x, ok := m.GetBalanceType().(*Listener_ConnectionBalanceConfig_ExactBalance_); ok {
		return x.ExactBalance
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Listener_ConnectionBalanceConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Listener_ConnectionBalanceConfig_ExactBalance_)(nil),
	}
}

type Listener_ConnectionBalanceConfig_ExactBalance struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listener_ConnectionBalanceConfig_ExactBalance) Reset() {
	*m = Listener_ConnectionBalanceConfig_ExactBalance{}
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) String() string {
	return proto.CompactTextString(m)
}
func (*Listener_ConnectionBalanceConfig_ExactBalance) ProtoMessage() {}
func (*Listener_ConnectionBalanceConfig_ExactBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f8f4b6e66505502, []int{0, 1, 0}
}

func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Unmarshal(m, b)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Marshal(b, m, deterministic)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Merge(m, src)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_Size() int {
	return xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.Size(m)
}
func (m *Listener_ConnectionBalanceConfig_ExactBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance.DiscardUnknown(m)
}

var xxx_messageInfo_Listener_ConnectionBalanceConfig_ExactBalance proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("envoy.api.v2.Listener_DrainType", Listener_DrainType_name, Listener_DrainType_value)
	proto.RegisterType((*Listener)(nil), "envoy.api.v2.Listener")
	proto.RegisterType((*Listener_DeprecatedV1)(nil), "envoy.api.v2.Listener.DeprecatedV1")
	proto.RegisterType((*Listener_ConnectionBalanceConfig)(nil), "envoy.api.v2.Listener.ConnectionBalanceConfig")
	proto.RegisterType((*Listener_ConnectionBalanceConfig_ExactBalance)(nil), "envoy.api.v2.Listener.ConnectionBalanceConfig.ExactBalance")
}

func init() { proto.RegisterFile("envoy/api/v2/listener.proto", fileDescriptor_0f8f4b6e66505502) }

var fileDescriptor_0f8f4b6e66505502 = []byte{
	// 971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x73, 0x1b, 0x35,
	0x14, 0xed, 0xe6, 0xa3, 0x71, 0x64, 0x3b, 0x71, 0x14, 0x68, 0x54, 0x37, 0xa5, 0x26, 0xa5, 0x33,
	0x66, 0x98, 0x59, 0x4f, 0x9d, 0x19, 0x78, 0xa0, 0x03, 0x13, 0xc7, 0x0d, 0x29, 0xe3, 0xd4, 0x61,
	0x9b, 0x74, 0xda, 0x27, 0x8d, 0xbc, 0xab, 0x75, 0x05, 0x6b, 0x49, 0x48, 0x5a, 0xd3, 0xfc, 0x05,
	0x5e, 0x78, 0xe5, 0x99, 0x7f, 0xc4, 0x5f, 0xe1, 0x89, 0xe1, 0x81, 0x61, 0x56, 0xfb, 0x91, 0x75,
	0x6c, 0x13, 0x78, 0x93, 0x74, 0xcf, 0x39, 0x7b, 0xef, 0xb9, 0x77, 0x2f, 0x78, 0x40, 0xf9, 0x54,
	0x5c, 0x75, 0x88, 0x64, 0x9d, 0x69, 0xb7, 0x13, 0x31, 0x6d, 0x28, 0xa7, 0xca, 0x95, 0x4a, 0x18,
	0x01, 0x6b, 0x36, 0xe8, 0x12, 0xc9, 0xdc, 0x69, 0xb7, 0xf9, 0x68, 0x06, 0xea, 0x0b, 0x45, 0x3b,
	0x24, 0x08, 0x14, 0xd5, 0x3a, 0x85, 0x37, 0xf7, 0xe7, 0x01, 0x23, 0xa2, 0x69, 0x16, 0x7d, 0x32,
	0x1f, 0xd5, 0xc2, 0xff, 0x81, 0x1a, 0x2c, 0xa4, 0x61, 0x82, 0x67, 0xb0, 0xce, 0xc2, 0x84, 0x8a,
	0x03, 0xf6, 0xc5, 0x44, 0x0a, 0x4e, 0xb9, 0xd1, 0xff, 0x4e, 0x88, 0x03, 0x89, 0x4b, 0x24, 0x1e,
	0xb2, 0x71, 0x46, 0xf8, 0x2c, 0x25, 0xa4, 0x6f, 0xd7, 0x84, 0x69, 0x37, 0xd1, 0xc0, 0xb3, 0x16,
	0x34, 0xf7, 0xc7, 0x42, 0x8c, 0x23, 0x6a, 0xe5, 0x09, 0xe7, 0xc2, 0x90, 0x24, 0xd7, 0xfc, 0xdb,
	0x1f, 0x65, 0x51, 0x7b, 0x1b, 0xc5, 0x61, 0x27, 0x88, 0x15, 0x29, 0x15, 0x33, 0x17, 0xff, 0x49,
	0x11, 0x29, 0xa9, 0x2a, 0xf8, 0x71, 0x20, 0x49, 0x59, 0xb7, 0x33, 0x61, 0x63, 0x45, 0x4c, 0xee,
	0xd9, 0xde, 0x94, 0x44, 0x2c, 0x20, 0x86, 0x76, 0xf2, 0x43, 0x1a, 0x38, 0xf8, 0xbd, 0x0e, 0x2a,
	0x83, 0x2c, 0x53, 0x08, 0xc1, 0x1a, 0x27, 0x13, 0x8a, 0x9c, 0x96, 0xd3, 0xde, 0xf4, 0xec, 0x19,
	0x7e, 0x05, 0x36, 0xb2, 0xe6, 0xa0, 0x95, 0x96, 0xd3, 0xae, 0x76, 0x9b, 0x6e, 0xb9, 0x99, 0x6e,
	0xe2, 0xbf, 0x7b, 0x94, 0x22, 0x7a, 0x95, 0xbf, 0x7a, 0xeb, 0x3f, 0x3b, 0x2b, 0x0d, 0xc7, 0xcb,
	0x49, 0xf0, 0x1b, 0x50, 0x0f, 0x59, 0x64, 0x12, 0xef, 0xde, 0x11, 0xc6, 0x35, 0x5a, 0x6d, 0xad,
	0xb6, 0xab, 0xdd, 0x83, 0x59, 0x95, 0xc2, 0xac, 0x13, 0x8b, 0x3d, 0x4e, 0xa0, 0x5e, 0x2d, 0xbc,
	0xbe, 0x68, 0x78, 0x0a, 0x1a, 0xb1, 0xa6, 0x58, 0x28, 0x36, 0x66, 0x9c, 0x44, 0x38, 0xd0, 0x06,
	0xad, 0x65, 0x19, 0xa5, 0xee, 0xb8, 0xb9, 0x3b, 0x6e, 0x4f, 0x88, 0xe8, 0x35, 0x89, 0x62, 0xda,
	0x5b, 0x41, 0x8e, 0xb7, 0x15, 0x6b, 0x3a, 0xcc, 0x68, 0x7d, 0x6d, 0x60, 0x08, 0x3e, 0x96, 0x69,
	0x2f, 0x39, 0xf5, 0x13, 0xb7, 0xf0, 0x28, 0x0e, 0x43, 0xaa, 0x70, 0xc4, 0x26, 0xcc, 0xe0, 0xd1,
	0x95, 0xa1, 0x1a, 0xad, 0x5b, 0xe9, 0xfd, 0x39, 0xe9, 0xcb, 0x17, 0xdc, 0x1c, 0x76, 0xad, 0xb8,
	0xf7, 0x50, 0x52, 0x75, 0x5c, 0xa8, 0xf4, 0xac, 0xc8, 0x20, 0xd1, 0xe8, 0x25, 0x12, 0xf0, 0x0b,
	0x50, 0x99, 0x50, 0x43, 0x02, 0x62, 0x08, 0xba, 0x6b, 0xe5, 0x1e, 0x2c, 0xf0, 0xee, 0x2c, 0x83,
	0x78, 0x05, 0x18, 0x9e, 0x82, 0x7a, 0x40, 0xa5, 0xa2, 0x3e, 0x31, 0x34, 0xc0, 0xd3, 0xa7, 0x68,
	0xc3, 0xb2, 0x1f, 0xcf, 0xb2, 0xf3, 0xb6, 0xb9, 0xfd, 0x02, 0xfb, 0xfa, 0xa9, 0x57, 0x0b, 0x4a,
	0x37, 0xf8, 0x35, 0x00, 0x81, 0x22, 0x8c, 0x63, 0x73, 0x25, 0x29, 0xaa, 0xb4, 0x9c, 0xf6, 0x56,
	0xb7, 0xb5, 0x4c, 0x26, 0x01, 0x5e, 0x5c, 0x49, 0xea, 0x6d, 0x06, 0xf9, 0x11, 0x9e, 0x83, 0x46,
	0x31, 0xfc, 0x69, 0x3b, 0x34, 0xda, 0xb4, 0x1d, 0x7c, 0xb2, 0xa4, 0x83, 0xb9, 0x5e, 0xda, 0x49,
	0x6f, 0x3b, 0x9a, 0xb9, 0x6b, 0xf8, 0x0a, 0xa0, 0x9b, 0x8a, 0xd8, 0xb0, 0x09, 0x15, 0xb1, 0x41,
	0xdb, 0xb6, 0xce, 0xfb, 0x73, 0xa6, 0xf7, 0xb3, 0xbf, 0xc1, 0xbb, 0x77, 0x43, 0xed, 0x22, 0x25,
	0xc2, 0x97, 0xe0, 0x13, 0x5f, 0x70, 0xc3, 0x78, 0x4c, 0xb1, 0xe0, 0x78, 0xe9, 0x07, 0x76, 0x5a,
	0x4e, 0xbb, 0xe2, 0xb5, 0x72, 0xec, 0x90, 0x0f, 0x16, 0xeb, 0x3d, 0x03, 0x55, 0xa3, 0x08, 0xd7,
	0x92, 0x28, 0xca, 0x0d, 0x02, 0xb7, 0xcd, 0x99, 0x57, 0x86, 0xc3, 0xcf, 0x41, 0x25, 0x54, 0x94,
	0x8e, 0x18, 0x0f, 0x50, 0xf5, 0x56, 0x6a, 0x81, 0x85, 0x27, 0x60, 0x6b, 0x66, 0x93, 0x69, 0x54,
	0xb7, 0x56, 0x3f, 0x5a, 0x30, 0x36, 0xaf, 0x2c, 0x70, 0x68, 0x71, 0x5e, 0x5d, 0x97, 0x6e, 0x1a,
	0xbe, 0x01, 0x4d, 0xe3, 0x4b, 0x1c, 0x12, 0x9d, 0x28, 0x51, 0x8e, 0x7f, 0x8c, 0x69, 0x4c, 0x71,
	0x44, 0xf9, 0xd8, 0xbc, 0x43, 0xb5, 0xff, 0x30, 0xd9, 0xf7, 0x8c, 0x2f, 0x4f, 0x88, 0x36, 0x43,
	0x49, 0xf9, 0x77, 0x09, 0x79, 0x60, 0xb9, 0xf0, 0x1c, 0xec, 0x18, 0x45, 0xc2, 0x90, 0xf9, 0x38,
	0x60, 0x2a, 0x9d, 0x7b, 0xd4, 0xb0, 0x63, 0xf5, 0x78, 0x41, 0x92, 0x17, 0x29, 0xb6, 0x9f, 0x43,
	0xbd, 0x86, 0xb9, 0xf1, 0x02, 0xdf, 0x80, 0xdd, 0x05, 0x1b, 0x16, 0x41, 0x9b, 0x64, 0x7b, 0xc9,
	0x8c, 0x5d, 0x06, 0x32, 0x6f, 0xdc, 0xb1, 0xc5, 0x7b, 0x3b, 0xf1, 0xcd, 0x27, 0x78, 0x0a, 0x6a,
	0xe5, 0x3d, 0x8c, 0x76, 0xad, 0x64, 0x3e, 0xb6, 0xd9, 0x26, 0x2f, 0x24, 0xa7, 0x5d, 0xf7, 0x48,
	0xb2, 0x5c, 0xc2, 0xab, 0x92, 0xeb, 0x0b, 0xfc, 0x1e, 0xdc, 0x2f, 0x2f, 0x0b, 0x12, 0x11, 0xee,
	0xd3, 0x3c, 0xd3, 0x0f, 0xac, 0xac, 0xbb, 0xe4, 0xa7, 0x2a, 0xad, 0x87, 0x94, 0x96, 0xe5, 0xbb,
	0xe7, 0x2f, 0x0e, 0xc0, 0x87, 0x00, 0x28, 0x9a, 0x2c, 0x3a, 0x29, 0x94, 0x41, 0x1f, 0xda, 0x79,
	0xdd, 0xb4, 0x2f, 0xe7, 0x42, 0x99, 0xe6, 0x00, 0xd4, 0xca, 0xbf, 0x3b, 0x7c, 0x06, 0x6a, 0xc9,
	0xe8, 0x60, 0x23, 0x52, 0x82, 0x73, 0xeb, 0xb8, 0x81, 0x04, 0x7f, 0x21, 0xac, 0xda, 0x6f, 0x0e,
	0xd8, 0x5b, 0x92, 0x21, 0x1c, 0x81, 0x3a, 0x7d, 0x4f, 0x7c, 0x93, 0xd7, 0x9b, 0x49, 0x7f, 0xf9,
	0xff, 0x0a, 0x75, 0x9f, 0x27, 0x1a, 0xd9, 0xd3, 0xe9, 0x1d, 0xaf, 0x46, 0x4b, 0xf7, 0xe6, 0x16,
	0xa8, 0x95, 0xe3, 0xbd, 0x5d, 0x50, 0xcb, 0xdd, 0x4d, 0x16, 0x16, 0x5c, 0xfd, 0xb3, 0xe7, 0x1c,
	0x7c, 0x0a, 0x36, 0x8b, 0xd5, 0x04, 0xab, 0x60, 0xa3, 0xff, 0xfc, 0xe4, 0xe8, 0x72, 0x70, 0xd1,
	0xb8, 0x03, 0xb7, 0x41, 0xf5, 0x6c, 0xd8, 0x7f, 0x71, 0xf2, 0x16, 0x0f, 0x5f, 0x0e, 0xde, 0x36,
	0x9c, 0x6f, 0xd7, 0x2a, 0x5b, 0x8d, 0xed, 0xde, 0xd9, 0x1f, 0xbf, 0xfe, 0xfd, 0xcb, 0x7a, 0x13,
	0xa2, 0x25, 0x9d, 0x3e, 0x04, 0x4d, 0x26, 0xd2, 0x32, 0xa4, 0x12, 0xef, 0xaf, 0x66, 0x2a, 0xea,
	0xd5, 0xf3, 0x92, 0xce, 0x13, 0xef, 0xce, 0x9d, 0xd1, 0x5d, 0x6b, 0xe2, 0xe1, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x2b, 0x1e, 0xed, 0xe2, 0x08, 0x00, 0x00,
}
