// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/trace/v3/trace.proto

package envoy_config_trace_v3

import (
	fmt "fmt"
	v1 "github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	_ "github.com/envoyproxy/go-control-plane/envoy/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ZipkinConfig_CollectorEndpointVersion int32

const (
	ZipkinConfig_hidden_envoy_deprecated_HTTP_JSON_V1 ZipkinConfig_CollectorEndpointVersion = 0 // Deprecated: Do not use.
	ZipkinConfig_HTTP_JSON                            ZipkinConfig_CollectorEndpointVersion = 1
	ZipkinConfig_HTTP_PROTO                           ZipkinConfig_CollectorEndpointVersion = 2
	ZipkinConfig_GRPC                                 ZipkinConfig_CollectorEndpointVersion = 3
)

var ZipkinConfig_CollectorEndpointVersion_name = map[int32]string{
	0: "hidden_envoy_deprecated_HTTP_JSON_V1",
	1: "HTTP_JSON",
	2: "HTTP_PROTO",
	3: "GRPC",
}

var ZipkinConfig_CollectorEndpointVersion_value = map[string]int32{
	"hidden_envoy_deprecated_HTTP_JSON_V1": 0,
	"HTTP_JSON":                            1,
	"HTTP_PROTO":                           2,
	"GRPC":                                 3,
}

func (x ZipkinConfig_CollectorEndpointVersion) String() string {
	return proto.EnumName(ZipkinConfig_CollectorEndpointVersion_name, int32(x))
}

func (ZipkinConfig_CollectorEndpointVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{2, 0}
}

type OpenCensusConfig_TraceContext int32

const (
	OpenCensusConfig_NONE                OpenCensusConfig_TraceContext = 0
	OpenCensusConfig_TRACE_CONTEXT       OpenCensusConfig_TraceContext = 1
	OpenCensusConfig_GRPC_TRACE_BIN      OpenCensusConfig_TraceContext = 2
	OpenCensusConfig_CLOUD_TRACE_CONTEXT OpenCensusConfig_TraceContext = 3
	OpenCensusConfig_B3                  OpenCensusConfig_TraceContext = 4
)

var OpenCensusConfig_TraceContext_name = map[int32]string{
	0: "NONE",
	1: "TRACE_CONTEXT",
	2: "GRPC_TRACE_BIN",
	3: "CLOUD_TRACE_CONTEXT",
	4: "B3",
}

var OpenCensusConfig_TraceContext_value = map[string]int32{
	"NONE":                0,
	"TRACE_CONTEXT":       1,
	"GRPC_TRACE_BIN":      2,
	"CLOUD_TRACE_CONTEXT": 3,
	"B3":                  4,
}

func (x OpenCensusConfig_TraceContext) String() string {
	return proto.EnumName(OpenCensusConfig_TraceContext_name, int32(x))
}

func (OpenCensusConfig_TraceContext) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{5, 0}
}

type Tracing struct {
	Http                 *Tracing_Http `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Tracing) Reset()         { *m = Tracing{} }
func (m *Tracing) String() string { return proto.CompactTextString(m) }
func (*Tracing) ProtoMessage()    {}
func (*Tracing) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{0}
}

func (m *Tracing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing.Unmarshal(m, b)
}
func (m *Tracing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing.Marshal(b, m, deterministic)
}
func (m *Tracing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing.Merge(m, src)
}
func (m *Tracing) XXX_Size() int {
	return xxx_messageInfo_Tracing.Size(m)
}
func (m *Tracing) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing proto.InternalMessageInfo

func (m *Tracing) GetHttp() *Tracing_Http {
	if m != nil {
		return m.Http
	}
	return nil
}

type Tracing_Http struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//	*Tracing_Http_HiddenEnvoyDeprecatedConfig
	//	*Tracing_Http_TypedConfig
	ConfigType           isTracing_Http_ConfigType `protobuf_oneof:"config_type"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Tracing_Http) Reset()         { *m = Tracing_Http{} }
func (m *Tracing_Http) String() string { return proto.CompactTextString(m) }
func (*Tracing_Http) ProtoMessage()    {}
func (*Tracing_Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{0, 0}
}

func (m *Tracing_Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracing_Http.Unmarshal(m, b)
}
func (m *Tracing_Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracing_Http.Marshal(b, m, deterministic)
}
func (m *Tracing_Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracing_Http.Merge(m, src)
}
func (m *Tracing_Http) XXX_Size() int {
	return xxx_messageInfo_Tracing_Http.Size(m)
}
func (m *Tracing_Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracing_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Tracing_Http proto.InternalMessageInfo

func (m *Tracing_Http) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isTracing_Http_ConfigType interface {
	isTracing_Http_ConfigType()
}

type Tracing_Http_HiddenEnvoyDeprecatedConfig struct {
	HiddenEnvoyDeprecatedConfig *_struct.Struct `protobuf:"bytes,2,opt,name=hidden_envoy_deprecated_config,json=hiddenEnvoyDeprecatedConfig,proto3,oneof"`
}

type Tracing_Http_TypedConfig struct {
	TypedConfig *any.Any `protobuf:"bytes,3,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*Tracing_Http_HiddenEnvoyDeprecatedConfig) isTracing_Http_ConfigType() {}

func (*Tracing_Http_TypedConfig) isTracing_Http_ConfigType() {}

func (m *Tracing_Http) GetConfigType() isTracing_Http_ConfigType {
	if m != nil {
		return m.ConfigType
	}
	return nil
}

// Deprecated: Do not use.
func (m *Tracing_Http) GetHiddenEnvoyDeprecatedConfig() *_struct.Struct {
	if x, ok := m.GetConfigType().(*Tracing_Http_HiddenEnvoyDeprecatedConfig); ok {
		return x.HiddenEnvoyDeprecatedConfig
	}
	return nil
}

func (m *Tracing_Http) GetTypedConfig() *any.Any {
	if x, ok := m.GetConfigType().(*Tracing_Http_TypedConfig); ok {
		return x.TypedConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tracing_Http) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tracing_Http_HiddenEnvoyDeprecatedConfig)(nil),
		(*Tracing_Http_TypedConfig)(nil),
	}
}

type LightstepConfig struct {
	CollectorCluster     string   `protobuf:"bytes,1,opt,name=collector_cluster,json=collectorCluster,proto3" json:"collector_cluster,omitempty"`
	AccessTokenFile      string   `protobuf:"bytes,2,opt,name=access_token_file,json=accessTokenFile,proto3" json:"access_token_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LightstepConfig) Reset()         { *m = LightstepConfig{} }
func (m *LightstepConfig) String() string { return proto.CompactTextString(m) }
func (*LightstepConfig) ProtoMessage()    {}
func (*LightstepConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{1}
}

func (m *LightstepConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightstepConfig.Unmarshal(m, b)
}
func (m *LightstepConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightstepConfig.Marshal(b, m, deterministic)
}
func (m *LightstepConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightstepConfig.Merge(m, src)
}
func (m *LightstepConfig) XXX_Size() int {
	return xxx_messageInfo_LightstepConfig.Size(m)
}
func (m *LightstepConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LightstepConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LightstepConfig proto.InternalMessageInfo

func (m *LightstepConfig) GetCollectorCluster() string {
	if m != nil {
		return m.CollectorCluster
	}
	return ""
}

func (m *LightstepConfig) GetAccessTokenFile() string {
	if m != nil {
		return m.AccessTokenFile
	}
	return ""
}

type ZipkinConfig struct {
	CollectorCluster         string                                `protobuf:"bytes,1,opt,name=collector_cluster,json=collectorCluster,proto3" json:"collector_cluster,omitempty"`
	CollectorEndpoint        string                                `protobuf:"bytes,2,opt,name=collector_endpoint,json=collectorEndpoint,proto3" json:"collector_endpoint,omitempty"`
	TraceId_128Bit           bool                                  `protobuf:"varint,3,opt,name=trace_id_128bit,json=traceId128bit,proto3" json:"trace_id_128bit,omitempty"`
	SharedSpanContext        *wrappers.BoolValue                   `protobuf:"bytes,4,opt,name=shared_span_context,json=sharedSpanContext,proto3" json:"shared_span_context,omitempty"`
	CollectorEndpointVersion ZipkinConfig_CollectorEndpointVersion `protobuf:"varint,5,opt,name=collector_endpoint_version,json=collectorEndpointVersion,proto3,enum=envoy.config.trace.v3.ZipkinConfig_CollectorEndpointVersion" json:"collector_endpoint_version,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                              `json:"-"`
	XXX_unrecognized         []byte                                `json:"-"`
	XXX_sizecache            int32                                 `json:"-"`
}

func (m *ZipkinConfig) Reset()         { *m = ZipkinConfig{} }
func (m *ZipkinConfig) String() string { return proto.CompactTextString(m) }
func (*ZipkinConfig) ProtoMessage()    {}
func (*ZipkinConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{2}
}

func (m *ZipkinConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZipkinConfig.Unmarshal(m, b)
}
func (m *ZipkinConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZipkinConfig.Marshal(b, m, deterministic)
}
func (m *ZipkinConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZipkinConfig.Merge(m, src)
}
func (m *ZipkinConfig) XXX_Size() int {
	return xxx_messageInfo_ZipkinConfig.Size(m)
}
func (m *ZipkinConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ZipkinConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ZipkinConfig proto.InternalMessageInfo

func (m *ZipkinConfig) GetCollectorCluster() string {
	if m != nil {
		return m.CollectorCluster
	}
	return ""
}

func (m *ZipkinConfig) GetCollectorEndpoint() string {
	if m != nil {
		return m.CollectorEndpoint
	}
	return ""
}

func (m *ZipkinConfig) GetTraceId_128Bit() bool {
	if m != nil {
		return m.TraceId_128Bit
	}
	return false
}

func (m *ZipkinConfig) GetSharedSpanContext() *wrappers.BoolValue {
	if m != nil {
		return m.SharedSpanContext
	}
	return nil
}

func (m *ZipkinConfig) GetCollectorEndpointVersion() ZipkinConfig_CollectorEndpointVersion {
	if m != nil {
		return m.CollectorEndpointVersion
	}
	return ZipkinConfig_hidden_envoy_deprecated_HTTP_JSON_V1
}

type DynamicOtConfig struct {
	Library              string          `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	Config               *_struct.Struct `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DynamicOtConfig) Reset()         { *m = DynamicOtConfig{} }
func (m *DynamicOtConfig) String() string { return proto.CompactTextString(m) }
func (*DynamicOtConfig) ProtoMessage()    {}
func (*DynamicOtConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{3}
}

func (m *DynamicOtConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicOtConfig.Unmarshal(m, b)
}
func (m *DynamicOtConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicOtConfig.Marshal(b, m, deterministic)
}
func (m *DynamicOtConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicOtConfig.Merge(m, src)
}
func (m *DynamicOtConfig) XXX_Size() int {
	return xxx_messageInfo_DynamicOtConfig.Size(m)
}
func (m *DynamicOtConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicOtConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicOtConfig proto.InternalMessageInfo

func (m *DynamicOtConfig) GetLibrary() string {
	if m != nil {
		return m.Library
	}
	return ""
}

func (m *DynamicOtConfig) GetConfig() *_struct.Struct {
	if m != nil {
		return m.Config
	}
	return nil
}

type DatadogConfig struct {
	CollectorCluster     string   `protobuf:"bytes,1,opt,name=collector_cluster,json=collectorCluster,proto3" json:"collector_cluster,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatadogConfig) Reset()         { *m = DatadogConfig{} }
func (m *DatadogConfig) String() string { return proto.CompactTextString(m) }
func (*DatadogConfig) ProtoMessage()    {}
func (*DatadogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{4}
}

func (m *DatadogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatadogConfig.Unmarshal(m, b)
}
func (m *DatadogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatadogConfig.Marshal(b, m, deterministic)
}
func (m *DatadogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatadogConfig.Merge(m, src)
}
func (m *DatadogConfig) XXX_Size() int {
	return xxx_messageInfo_DatadogConfig.Size(m)
}
func (m *DatadogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DatadogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DatadogConfig proto.InternalMessageInfo

func (m *DatadogConfig) GetCollectorCluster() string {
	if m != nil {
		return m.CollectorCluster
	}
	return ""
}

func (m *DatadogConfig) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type OpenCensusConfig struct {
	TraceConfig                *v1.TraceConfig                 `protobuf:"bytes,1,opt,name=trace_config,json=traceConfig,proto3" json:"trace_config,omitempty"`
	StdoutExporterEnabled      bool                            `protobuf:"varint,2,opt,name=stdout_exporter_enabled,json=stdoutExporterEnabled,proto3" json:"stdout_exporter_enabled,omitempty"`
	StackdriverExporterEnabled bool                            `protobuf:"varint,3,opt,name=stackdriver_exporter_enabled,json=stackdriverExporterEnabled,proto3" json:"stackdriver_exporter_enabled,omitempty"`
	StackdriverProjectId       string                          `protobuf:"bytes,4,opt,name=stackdriver_project_id,json=stackdriverProjectId,proto3" json:"stackdriver_project_id,omitempty"`
	StackdriverAddress         string                          `protobuf:"bytes,10,opt,name=stackdriver_address,json=stackdriverAddress,proto3" json:"stackdriver_address,omitempty"`
	ZipkinExporterEnabled      bool                            `protobuf:"varint,5,opt,name=zipkin_exporter_enabled,json=zipkinExporterEnabled,proto3" json:"zipkin_exporter_enabled,omitempty"`
	ZipkinUrl                  string                          `protobuf:"bytes,6,opt,name=zipkin_url,json=zipkinUrl,proto3" json:"zipkin_url,omitempty"`
	OcagentExporterEnabled     bool                            `protobuf:"varint,11,opt,name=ocagent_exporter_enabled,json=ocagentExporterEnabled,proto3" json:"ocagent_exporter_enabled,omitempty"`
	OcagentAddress             string                          `protobuf:"bytes,12,opt,name=ocagent_address,json=ocagentAddress,proto3" json:"ocagent_address,omitempty"`
	IncomingTraceContext       []OpenCensusConfig_TraceContext `protobuf:"varint,8,rep,packed,name=incoming_trace_context,json=incomingTraceContext,proto3,enum=envoy.config.trace.v3.OpenCensusConfig_TraceContext" json:"incoming_trace_context,omitempty"`
	OutgoingTraceContext       []OpenCensusConfig_TraceContext `protobuf:"varint,9,rep,packed,name=outgoing_trace_context,json=outgoingTraceContext,proto3,enum=envoy.config.trace.v3.OpenCensusConfig_TraceContext" json:"outgoing_trace_context,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                        `json:"-"`
	XXX_unrecognized           []byte                          `json:"-"`
	XXX_sizecache              int32                           `json:"-"`
}

func (m *OpenCensusConfig) Reset()         { *m = OpenCensusConfig{} }
func (m *OpenCensusConfig) String() string { return proto.CompactTextString(m) }
func (*OpenCensusConfig) ProtoMessage()    {}
func (*OpenCensusConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{5}
}

func (m *OpenCensusConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenCensusConfig.Unmarshal(m, b)
}
func (m *OpenCensusConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenCensusConfig.Marshal(b, m, deterministic)
}
func (m *OpenCensusConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenCensusConfig.Merge(m, src)
}
func (m *OpenCensusConfig) XXX_Size() int {
	return xxx_messageInfo_OpenCensusConfig.Size(m)
}
func (m *OpenCensusConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenCensusConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OpenCensusConfig proto.InternalMessageInfo

func (m *OpenCensusConfig) GetTraceConfig() *v1.TraceConfig {
	if m != nil {
		return m.TraceConfig
	}
	return nil
}

func (m *OpenCensusConfig) GetStdoutExporterEnabled() bool {
	if m != nil {
		return m.StdoutExporterEnabled
	}
	return false
}

func (m *OpenCensusConfig) GetStackdriverExporterEnabled() bool {
	if m != nil {
		return m.StackdriverExporterEnabled
	}
	return false
}

func (m *OpenCensusConfig) GetStackdriverProjectId() string {
	if m != nil {
		return m.StackdriverProjectId
	}
	return ""
}

func (m *OpenCensusConfig) GetStackdriverAddress() string {
	if m != nil {
		return m.StackdriverAddress
	}
	return ""
}

func (m *OpenCensusConfig) GetZipkinExporterEnabled() bool {
	if m != nil {
		return m.ZipkinExporterEnabled
	}
	return false
}

func (m *OpenCensusConfig) GetZipkinUrl() string {
	if m != nil {
		return m.ZipkinUrl
	}
	return ""
}

func (m *OpenCensusConfig) GetOcagentExporterEnabled() bool {
	if m != nil {
		return m.OcagentExporterEnabled
	}
	return false
}

func (m *OpenCensusConfig) GetOcagentAddress() string {
	if m != nil {
		return m.OcagentAddress
	}
	return ""
}

func (m *OpenCensusConfig) GetIncomingTraceContext() []OpenCensusConfig_TraceContext {
	if m != nil {
		return m.IncomingTraceContext
	}
	return nil
}

func (m *OpenCensusConfig) GetOutgoingTraceContext() []OpenCensusConfig_TraceContext {
	if m != nil {
		return m.OutgoingTraceContext
	}
	return nil
}

type TraceServiceConfig struct {
	GrpcService          *v3.GrpcService `protobuf:"bytes,1,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TraceServiceConfig) Reset()         { *m = TraceServiceConfig{} }
func (m *TraceServiceConfig) String() string { return proto.CompactTextString(m) }
func (*TraceServiceConfig) ProtoMessage()    {}
func (*TraceServiceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8ab8dce64ff7a05, []int{6}
}

func (m *TraceServiceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceServiceConfig.Unmarshal(m, b)
}
func (m *TraceServiceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceServiceConfig.Marshal(b, m, deterministic)
}
func (m *TraceServiceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceServiceConfig.Merge(m, src)
}
func (m *TraceServiceConfig) XXX_Size() int {
	return xxx_messageInfo_TraceServiceConfig.Size(m)
}
func (m *TraceServiceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceServiceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TraceServiceConfig proto.InternalMessageInfo

func (m *TraceServiceConfig) GetGrpcService() *v3.GrpcService {
	if m != nil {
		return m.GrpcService
	}
	return nil
}

func init() {
	proto.RegisterEnum("envoy.config.trace.v3.ZipkinConfig_CollectorEndpointVersion", ZipkinConfig_CollectorEndpointVersion_name, ZipkinConfig_CollectorEndpointVersion_value)
	proto.RegisterEnum("envoy.config.trace.v3.OpenCensusConfig_TraceContext", OpenCensusConfig_TraceContext_name, OpenCensusConfig_TraceContext_value)
	proto.RegisterType((*Tracing)(nil), "envoy.config.trace.v3.Tracing")
	proto.RegisterType((*Tracing_Http)(nil), "envoy.config.trace.v3.Tracing.Http")
	proto.RegisterType((*LightstepConfig)(nil), "envoy.config.trace.v3.LightstepConfig")
	proto.RegisterType((*ZipkinConfig)(nil), "envoy.config.trace.v3.ZipkinConfig")
	proto.RegisterType((*DynamicOtConfig)(nil), "envoy.config.trace.v3.DynamicOtConfig")
	proto.RegisterType((*DatadogConfig)(nil), "envoy.config.trace.v3.DatadogConfig")
	proto.RegisterType((*OpenCensusConfig)(nil), "envoy.config.trace.v3.OpenCensusConfig")
	proto.RegisterType((*TraceServiceConfig)(nil), "envoy.config.trace.v3.TraceServiceConfig")
}

func init() { proto.RegisterFile("envoy/config/trace/v3/trace.proto", fileDescriptor_a8ab8dce64ff7a05) }

var fileDescriptor_a8ab8dce64ff7a05 = []byte{
	// 1159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x17, 0x35, 0x65, 0xc5, 0x96, 0xaf, 0x64, 0x9b, 0x9e, 0xfc, 0x58, 0x9f, 0xf2, 0xf3, 0xd9, 0x72,
	0x7e, 0xdc, 0x20, 0x95, 0x60, 0x29, 0x48, 0x53, 0xa1, 0x8b, 0x46, 0xb2, 0x1a, 0xdb, 0x08, 0x24,
	0x81, 0x56, 0x8c, 0xa2, 0x1b, 0x76, 0x44, 0x8e, 0x65, 0xc6, 0xf4, 0x0c, 0x31, 0x1c, 0x29, 0x56,
	0x9e, 0xa0, 0x68, 0x37, 0x05, 0x8a, 0x6e, 0x0a, 0x74, 0x5f, 0x74, 0xdd, 0x57, 0xe8, 0xb3, 0xe4,
	0x11, 0x0a, 0x04, 0x5d, 0x14, 0x9c, 0x21, 0x2d, 0x8a, 0x96, 0x9a, 0x02, 0xde, 0x69, 0xee, 0xb9,
	0xe7, 0xcc, 0xb9, 0x77, 0xe6, 0x0e, 0x05, 0x9b, 0x84, 0x0e, 0xd9, 0xa8, 0x6c, 0x31, 0x7a, 0xec,
	0xf4, 0xcb, 0x82, 0x63, 0x8b, 0x94, 0x87, 0x55, 0xf5, 0xa3, 0xe4, 0x71, 0x26, 0x18, 0xba, 0x29,
	0x53, 0x4a, 0x2a, 0xa5, 0xa4, 0x90, 0x61, 0xb5, 0xf0, 0x68, 0x82, 0x69, 0x31, 0x2e, 0x89, 0x7d,
	0xee, 0x59, 0xa6, 0x4f, 0xf8, 0xd0, 0x89, 0xf8, 0x85, 0xff, 0xf5, 0x19, 0xeb, 0xbb, 0xa4, 0x2c,
	0x57, 0xbd, 0xc1, 0x71, 0x19, 0xd3, 0x51, 0x08, 0xdd, 0x49, 0x42, 0xbe, 0xe0, 0x03, 0x4b, 0x84,
	0xe8, 0xbd, 0x24, 0xfa, 0x96, 0x63, 0xcf, 0x23, 0xdc, 0x0f, 0xf1, 0x27, 0xcc, 0x23, 0xd4, 0x22,
	0xd4, 0x1f, 0xf8, 0x2a, 0x27, 0xf2, 0xbf, 0xa3, 0x7e, 0x98, 0xa1, 0x65, 0x95, 0xbd, 0x39, 0xb0,
	0x3d, 0x5c, 0xc6, 0x94, 0x32, 0x81, 0x85, 0xc3, 0xa8, 0x5f, 0x1e, 0x12, 0xee, 0x3b, 0x8c, 0x3a,
	0x34, 0x4a, 0xd9, 0x52, 0x25, 0xc5, 0x73, 0x6c, 0xe2, 0x71, 0x62, 0xc9, 0x45, 0x98, 0xb4, 0x3e,
	0xc4, 0xae, 0x63, 0x63, 0x41, 0xca, 0xd1, 0x0f, 0x05, 0x14, 0xdf, 0xa7, 0x60, 0xb1, 0xcb, 0xb1,
	0xe5, 0xd0, 0x3e, 0xfa, 0x0c, 0xd2, 0x27, 0x42, 0x78, 0x79, 0x6d, 0x43, 0xdb, 0xce, 0x56, 0xb6,
	0x4a, 0x53, 0x5b, 0x58, 0x0a, 0xb3, 0x4b, 0x7b, 0x42, 0x78, 0x86, 0x24, 0x14, 0xfe, 0xd6, 0x20,
	0x1d, 0x2c, 0xd1, 0x6d, 0x48, 0x53, 0x7c, 0x46, 0xa4, 0xc2, 0x52, 0x7d, 0xf1, 0x43, 0x3d, 0xcd,
	0x53, 0x1b, 0x9a, 0x21, 0x83, 0xa8, 0x07, 0xf7, 0x4e, 0x1c, 0xdb, 0x26, 0xd4, 0x94, 0xc2, 0x66,
	0xe4, 0x92, 0xd8, 0x61, 0xcd, 0xf9, 0x94, 0xdc, 0x78, 0xbd, 0xa4, 0x5a, 0x58, 0x8a, 0x5a, 0x58,
	0x3a, 0x94, 0x0d, 0xae, 0xa7, 0xf2, 0xda, 0xde, 0x9c, 0x71, 0x5b, 0x89, 0x34, 0x03, 0x8d, 0xdd,
	0x0b, 0x89, 0x86, 0x54, 0x40, 0x9f, 0x43, 0x4e, 0x8c, 0xbc, 0xb1, 0xe2, 0xbc, 0x54, 0xbc, 0x71,
	0x49, 0xf1, 0x05, 0x1d, 0xed, 0xcd, 0x19, 0x59, 0x99, 0xab, 0xa8, 0xb5, 0x4f, 0x7e, 0xf9, 0xf3,
	0xbb, 0x7b, 0xf7, 0xa1, 0x38, 0xad, 0xea, 0xca, 0x44, 0xd5, 0xf5, 0x65, 0xc8, 0x2a, 0xdc, 0x0c,
	0x04, 0x6a, 0xf7, 0x03, 0xe6, 0xff, 0xe1, 0xee, 0xbf, 0x32, 0x8b, 0xbf, 0x6b, 0xb0, 0xfa, 0xca,
	0xe9, 0x9f, 0x08, 0x5f, 0x10, 0x2f, 0xb4, 0xfb, 0x14, 0xd6, 0x2c, 0xe6, 0xba, 0xc4, 0x12, 0x8c,
	0x9b, 0x96, 0x3b, 0xf0, 0x05, 0xe1, 0xc9, 0xe6, 0xe9, 0x17, 0x19, 0x0d, 0x95, 0x80, 0xaa, 0xb0,
	0x86, 0x2d, 0x8b, 0xf8, 0xbe, 0x29, 0xd8, 0x29, 0xa1, 0xe6, 0xb1, 0xe3, 0x12, 0xd9, 0xbb, 0x18,
	0x6b, 0x55, 0x65, 0x74, 0x83, 0x84, 0xaf, 0x1c, 0x97, 0xd4, 0x9e, 0x04, 0x26, 0x1f, 0xc1, 0x83,
	0xe9, 0x26, 0x13, 0xc6, 0x8a, 0x3f, 0xa6, 0x21, 0xf7, 0x8d, 0xe3, 0x9d, 0x3a, 0xf4, 0x4a, 0x4e,
	0x9f, 0x01, 0x1a, 0xb3, 0x08, 0xb5, 0x3d, 0xe6, 0x50, 0x91, 0xb4, 0x3a, 0x16, 0x6e, 0x86, 0x19,
	0xe8, 0x21, 0xac, 0xaa, 0x61, 0x70, 0x6c, 0x73, 0xa7, 0xf2, 0xbc, 0xe7, 0x08, 0x79, 0x92, 0x19,
	0x63, 0x59, 0x86, 0xf7, 0x6d, 0x15, 0x44, 0x07, 0x70, 0xdd, 0x3f, 0xc1, 0x9c, 0xd8, 0xa6, 0xef,
	0x61, 0x1a, 0x1c, 0xba, 0x20, 0xe7, 0x22, 0x9f, 0x96, 0xa7, 0x5e, 0xb8, 0x74, 0xea, 0x75, 0xc6,
	0xdc, 0x23, 0xec, 0x0e, 0x88, 0xb1, 0xa6, 0x68, 0x87, 0x1e, 0x0e, 0x0a, 0x0c, 0x48, 0xe8, 0x1d,
	0x14, 0x2e, 0x7b, 0x35, 0xc3, 0x71, 0xcb, 0x5f, 0xdb, 0xd0, 0xb6, 0x57, 0x2a, 0x5f, 0xcc, 0x98,
	0x89, 0x78, 0xab, 0x4a, 0x8d, 0x64, 0x39, 0x47, 0x4a, 0xc3, 0xc8, 0x5b, 0x33, 0x90, 0xe2, 0x5b,
	0xc8, 0xcf, 0x62, 0xa1, 0x0a, 0xdc, 0x9f, 0x35, 0x36, 0x7b, 0xdd, 0x6e, 0xc7, 0x3c, 0x38, 0x6c,
	0xb7, 0xcc, 0xa3, 0x1d, 0x7d, 0xae, 0x90, 0xf9, 0xed, 0xaf, 0x3f, 0x7e, 0x48, 0x69, 0x19, 0x0d,
	0x2d, 0xc3, 0xd2, 0x05, 0xa6, 0x6b, 0x68, 0x05, 0x40, 0x2e, 0x3b, 0x46, 0xbb, 0xdb, 0xd6, 0x53,
	0x28, 0x03, 0xe9, 0x97, 0x46, 0xa7, 0xa1, 0xcf, 0x7f, 0xe4, 0xd2, 0xc7, 0xcb, 0x2a, 0xfe, 0xa4,
	0xc1, 0xea, 0xee, 0x88, 0xe2, 0x33, 0xc7, 0x6a, 0x8b, 0xf0, 0x56, 0x6c, 0xc2, 0xa2, 0xeb, 0xf4,
	0x38, 0xe6, 0xa3, 0xe4, 0x5d, 0x88, 0xe2, 0xa8, 0x0c, 0x0b, 0xff, 0x69, 0xba, 0x8d, 0x30, 0xed,
	0x23, 0x17, 0x35, 0xe1, 0xa0, 0xf8, 0xab, 0x06, 0xcb, 0xbb, 0x58, 0x60, 0x9b, 0xf5, 0xaf, 0x74,
	0x53, 0x1f, 0x43, 0x2e, 0xfc, 0x00, 0x98, 0xf2, 0x05, 0x4b, 0xdc, 0xd1, 0x6c, 0x08, 0xb6, 0xf0,
	0x19, 0xa9, 0x3d, 0x0e, 0x1c, 0x3e, 0x80, 0xad, 0x19, 0x0e, 0xe3, 0x6e, 0x8a, 0xef, 0x17, 0x40,
	0x6f, 0x7b, 0x84, 0x36, 0xe4, 0x8b, 0x1f, 0x5a, 0xdc, 0x87, 0x5c, 0xfc, 0xad, 0x0f, 0x1f, 0xdc,
	0x87, 0xa5, 0xf1, 0xa7, 0x41, 0x75, 0x27, 0x12, 0xdd, 0x91, 0x8f, 0x08, 0x51, 0x6c, 0x23, 0x2b,
	0xc6, 0x0b, 0xf4, 0x0c, 0xd6, 0x7d, 0x61, 0xb3, 0x81, 0x30, 0xc9, 0xb9, 0xc7, 0xb8, 0x20, 0xc1,
	0xdd, 0xc5, 0x3d, 0x97, 0xd8, 0xb2, 0x84, 0x8c, 0x71, 0x53, 0xc1, 0xcd, 0x10, 0x6d, 0x2a, 0x10,
	0x7d, 0x09, 0x77, 0x7c, 0x81, 0xad, 0x53, 0x9b, 0x3b, 0xc3, 0x80, 0x93, 0x24, 0xab, 0x71, 0x2b,
	0xc4, 0x72, 0x92, 0x0a, 0x4f, 0xe1, 0x56, 0x5c, 0xc1, 0xe3, 0xec, 0x0d, 0xb1, 0x84, 0xe9, 0xd8,
	0x72, 0xfc, 0x96, 0x8c, 0x1b, 0x31, 0xb4, 0xa3, 0xc0, 0x7d, 0x1b, 0x95, 0xe1, 0x7a, 0x9c, 0x85,
	0x6d, 0x9b, 0x13, 0xdf, 0xcf, 0x83, 0xa4, 0xa0, 0x18, 0xf4, 0x42, 0x21, 0x41, 0x81, 0xef, 0xe4,
	0x35, 0xbc, 0xec, 0xf1, 0x9a, 0x2a, 0x50, 0xc1, 0x49, 0x7b, 0x77, 0x01, 0x42, 0xde, 0x80, 0xbb,
	0xf9, 0x05, 0xa9, 0xbf, 0xa4, 0x22, 0xaf, 0xb9, 0x8b, 0x9e, 0x43, 0x9e, 0x59, 0xb8, 0x4f, 0xe8,
	0x94, 0xc6, 0x65, 0xa5, 0xee, 0xad, 0x10, 0x4f, 0x0a, 0x3f, 0x82, 0xd5, 0x88, 0x19, 0xb9, 0xcf,
	0x49, 0xf5, 0x95, 0x30, 0x1c, 0x39, 0x7f, 0x03, 0xb7, 0x1c, 0x6a, 0xb1, 0x33, 0x87, 0xf6, 0xcd,
	0x8b, 0xe3, 0x96, 0xef, 0x53, 0x66, 0x63, 0x7e, 0x7b, 0xa5, 0xf2, 0x74, 0xc6, 0x63, 0x92, 0xbc,
	0x2e, 0x17, 0x87, 0x1f, 0x70, 0x8d, 0x1b, 0x91, 0x66, 0x3c, 0x1a, 0xec, 0xc5, 0x06, 0xa2, 0xcf,
	0x2e, 0xef, 0xb5, 0x74, 0x95, 0xbd, 0x22, 0xcd, 0x78, 0xb4, 0xf8, 0x2d, 0xe4, 0x26, 0xf6, 0xce,
	0x40, 0xba, 0xd5, 0x6e, 0x35, 0xf5, 0x39, 0xb4, 0x06, 0xcb, 0x5d, 0xe3, 0x45, 0xa3, 0x69, 0x36,
	0xda, 0xad, 0x6e, 0xf3, 0xeb, 0xae, 0xae, 0x21, 0x04, 0x2b, 0xc1, 0x53, 0x63, 0xaa, 0x78, 0x7d,
	0xbf, 0xa5, 0xa7, 0xd0, 0x3a, 0x5c, 0x6f, 0xbc, 0x6a, 0xbf, 0xde, 0x35, 0x27, 0x93, 0xe7, 0xd1,
	0x02, 0xa4, 0xea, 0x55, 0x3d, 0x5d, 0xfb, 0x34, 0x18, 0xb0, 0x6d, 0x78, 0x38, 0x7d, 0xc0, 0x92,
	0x9e, 0x0f, 0xd2, 0x99, 0x45, 0x3d, 0x53, 0xfc, 0x59, 0x03, 0x24, 0x7d, 0x1d, 0xaa, 0x51, 0x0d,
	0x07, 0xa4, 0x05, 0xb9, 0xf8, 0xdf, 0xbb, 0x70, 0xd6, 0x36, 0x27, 0xfb, 0x11, 0xfc, 0x11, 0x0c,
	0xda, 0xf1, 0x92, 0x7b, 0x56, 0x48, 0xaf, 0x67, 0x3e, 0xd4, 0xaf, 0x7d, 0xaf, 0xa5, 0x74, 0xcd,
	0xc8, 0xf6, 0xc7, 0xe1, 0x5a, 0x39, 0xf0, 0xf6, 0x18, 0xb6, 0x67, 0x7f, 0xec, 0x27, 0x0d, 0xd4,
	0xab, 0xb0, 0xe5, 0x30, 0xb5, 0x9d, 0xc7, 0xd9, 0xf9, 0x68, 0xfa, 0x49, 0xd4, 0x41, 0x52, 0x3b,
	0xc1, 0xd8, 0x77, 0xb4, 0xde, 0x82, 0x9c, 0xff, 0xea, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5,
	0x96, 0x74, 0x8c, 0xea, 0x0a, 0x00, 0x00,
}
