// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: envoy/extensions/formatter/file_content/v3/file_content.proto

package file_contentv3

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileContent formatter extension implements the “%FILE_CONTENT(/path/to/file)%“ command operator
// that reads the contents of the specified file. File-based data is automatically re-read when the
// file is modified on disk.
//
// Optionally, a directory to watch for changes can be specified with a
// colon followed by the directory to watch, eg “%FILE_CONTENT(/path/to/file:/path/to/watch)%“.
// See :ref:`watched_directory <envoy_v3_api_field_config.core.v3.DataSource.watched_directory>` for
// detailed semantics.
type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_envoy_extensions_formatter_file_content_v3_file_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_formatter_file_content_v3_file_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescGZIP(), []int{0}
}

var File_envoy_extensions_formatter_file_content_v3_file_content_proto protoreflect.FileDescriptor

const file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDesc = "" +
	"\n" +
	"=envoy/extensions/formatter/file_content/v3/file_content.proto\x12*envoy.extensions.formatter.file_content.v3\x1a\x1dudpa/annotations/status.proto\"\r\n" +
	"\vFileContentB\xb8\x01\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"8io.envoyproxy.envoy.extensions.formatter.file_content.v3B\x10FileContentProtoP\x01Z`github.com/envoyproxy/go-control-plane/envoy/extensions/formatter/file_content/v3;file_contentv3b\x06proto3"

var (
	file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescOnce sync.Once
	file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescData []byte
)

func file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescGZIP() []byte {
	file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDesc), len(file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDesc)))
	})
	return file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDescData
}

var file_envoy_extensions_formatter_file_content_v3_file_content_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_formatter_file_content_v3_file_content_proto_goTypes = []any{
	(*FileContent)(nil), // 0: envoy.extensions.formatter.file_content.v3.FileContent
}
var file_envoy_extensions_formatter_file_content_v3_file_content_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_envoy_extensions_formatter_file_content_v3_file_content_proto_init() }
func file_envoy_extensions_formatter_file_content_v3_file_content_proto_init() {
	if File_envoy_extensions_formatter_file_content_v3_file_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDesc), len(file_envoy_extensions_formatter_file_content_v3_file_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_formatter_file_content_v3_file_content_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_formatter_file_content_v3_file_content_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_formatter_file_content_v3_file_content_proto_msgTypes,
	}.Build()
	File_envoy_extensions_formatter_file_content_v3_file_content_proto = out.File
	file_envoy_extensions_formatter_file_content_v3_file_content_proto_goTypes = nil
	file_envoy_extensions_formatter_file_content_v3_file_content_proto_depIdxs = nil
}
