run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - gofmt
  - goimports
  - golint
  - gosec
  - misspell
  - revive
  - unconvert
  - unparam

linters-settings:
  misspell:
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  goimports:
    local-prefixes: github.com/envoyproxy/go-control-plane

issues:
  exclude:
  exclude-rules:
  - text: "SA1019: package github.com/golang/protobuf/jsonpb is deprecated"
    linters:
    - staticcheck
  - text: "SA1019: package github.com/golang/protobuf/proto is deprecated"
    linters:
    - staticcheck
  - text: "SA1019: proto.MessageName is deprecated"
    linters:
    - staticcheck
