name: golangci-lint

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci-lint:
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee  # v9.2.1
        with:
          version: latest
          only-new-issues: false
          # Optional: golangci-lint command line arguments.
          args: --verbose
